### ISSUE TITLE
Not able to use T3 Custom  Channel 

### ISSUE THREAD

**Issue by manavtidhan** [oracle/weblogic-deploy-tooling#1003]
Hi , I am getting below error when I called the from one domain to another domain which are in differnet namespace.

2021-11-12 09:48:53,257 ERROR  243439409 z.c.d.v.w.b.w.i.SaveAssessmentBusiness:421 - SaveAssessmentAndGenerateFeedback exception occurred
javax.ejb.EJBException: Unable to save assessment for entity 5501669534 on Fri Nov 12 00:01:10 GMT 2021
        at za.co.discovery.vitality.wellness.SaveAssessmentResultsProcessor.process(SaveAssessmentResultsProcessor.java:95) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.j2ee.session.AssessmentsSessionBean.saveAssessmentAndGenerateFeedback(AssessmentsSessionBean.java:435) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.j2ee.session.AssessmentsSession_9tbli2_ELOImpl.__WL_invoke(Unknown Source) ~[null:na]
        at weblogic.ejb.container.internal.SessionLocalMethodInvoker.invoke(SessionLocalMethodInvoker.java:33) ~[com.oracle.weblogic.ejb.jar:12.2.1.4]
        at za.co.discovery.vitality.wellness.j2ee.session.AssessmentsSession_9tbli2_ELOImpl.saveAssessmentAndGenerateFeedback(Unknown Source) ~[null:na]
        at za.co.discovery.vitality.wellness.business.wellnessService.impl.ResultsUploaderImpl.saveAssessmentAndGenerateFeedback(ResultsUploaderImpl.java:171) ~[_wl_cls_gen.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at com.sun.proxy.$Proxy227.saveAssessmentAndGenerateFeedback(Unknown Source) ~[na:na]
        at za.co.discovery.vitality.wellness.business.wellnessService.impl.SaveAssessmentBusiness.saveAssessmentAndGenerateFeedback(SaveAssessmentBusiness.java:100) ~[_wl_cls_gen.jar:na]
        at za.co.discovery.vitality.wellness.service.wellnessService.impl.OnlineAssessmentCaptureEndPoint.processRequest(OnlineAssessmentCaptureEndPoint.java:30) [_wl_cls_gen.jar:na]
        at za.co.discovery.vitality.wellness.web.AbstractWellnessEndpoint.invokeInternal(AbstractWellnessEndpoint.java:97) [_wl_cls_gen.jar:na]
        at org.springframework.ws.server.endpoint.AbstractMarshallingPayloadEndpoint.invoke(AbstractMarshallingPayloadEndpoint.java:135) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.server.endpoint.adapter.MessageEndpointAdapter.invoke(MessageEndpointAdapter.java:43) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:236) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:176) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:89) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:61) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:293) [spring-ws-core-3.0.1.RELEASE.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) [spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet.javax.servlet-api.jar:3.1.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) [spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet.javax.servlet-api.jar:3.1.0]
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at za.co.discovery.vitality.wellness.web.SpringContextFilter.doFilter(SpringContextFilter.java:51) [_wl_cls_gen.jar:na]
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3797) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3763) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344) [com.oracle.weblogic.security.subject.jar:12.2.1.4]
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197) [com.oracle.weblogic.security.subject.jar:12.2.1.4]
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1720) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1680) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272) [com.oracle.weblogic.servlet.jar:12.2.1.4]
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352) [com.bea.core.utils.full.jar:12.2.1.4]
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337) [com.bea.core.utils.full.jar:12.2.1.4]
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57) [com.oracle.weblogic.work.jar:12.2.1.4]
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41) [com.bea.core.weblogic.workmanager.jar:12.2.1.4]
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655) [com.bea.core.weblogic.workmanager.jar:12.2.1.4]
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420) [com.bea.core.weblogic.workmanager.jar:12.2.1.4]
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:360) [com.bea.core.weblogic.workmanager.jar:12.2.1.4]
Caused by: java.lang.RuntimeException: Couldn't look up InsertEventRemote from JNDI!
        at za.co.discovery.vitality.wellness.processor.BatchAttributeProcessorInsertEvent.lookupInsertEventEjb(BatchAttributeProcessorInsertEvent.java:154) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.processor.BatchAttributeProcessorInsertEvent.insertEvents(BatchAttributeProcessorInsertEvent.java:65) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.processor.BatchAttributeProcessor.insertNewEvents(BatchAttributeProcessor.java:339) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.processor.BatchAttributeProcessor.insertEvents(BatchAttributeProcessor.java:207) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.SaveAssessmentResultsProcessor.uploadRequest(SaveAssessmentResultsProcessor.java:315) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.SaveAssessmentResultsProcessor.processSaveAssessmentRequest(SaveAssessmentResultsProcessor.java:104) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        at za.co.discovery.vitality.wellness.SaveAssessmentResultsProcessor.process(SaveAssessmentResultsProcessor.java:89) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        ... 58 common frames omitted
Caused by: javax.naming.CommunicationException: This RJVM has already been shutdown 172311245397661906S:172.26.108.49:[33413,-1,-1,-1,-1,-1,-1]:vitality-core-points-domain:m2
        at weblogic.jndi.internal.ExceptionTranslator.toNamingException(ExceptionTranslator.java:68) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        at weblogic.jndi.internal.ExceptionTranslator.toNamingException(ExceptionTranslator.java:36) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        at weblogic.jndi.internal.WLContextImpl.translateException(WLContextImpl.java:541) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:453) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:435) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[na:1.8.0_291]
        at za.co.discovery.vitality.wellness.processor.BatchAttributeProcessorInsertEvent.lookupInsertEventEjb(BatchAttributeProcessorInsertEvent.java:151) ~[vitality-wellness-ejb-support-11.0.0.jar:na]
        ... 64 common frames omitted
Caused by: java.rmi.ConnectException: This RJVM has already been shutdown 172311245397661906S:172.26.108.49:[33413,-1,-1,-1,-1,-1,-1]:vitality-core-points-domain:m2
        at weblogic.rjvm.RJVMImpl.connectionCheck(RJVMImpl.java:843) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rjvm.RJVMImpl.getOutputStreamByURL(RJVMImpl.java:464) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rjvm.RJVMImpl.getMsgAbbrevOutputStream(RJVMImpl.java:802) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rjvm.RJVMImpl.getRequestStream(RJVMImpl.java:793) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rjvm.RJVMImpl.getOutboundRequest(RJVMImpl.java:1052) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rmi.internal.BasicRemoteRef.getRequest(BasicRemoteRef.java:237) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rmi.internal.BasicRemoteRef.getOutboundRequest(BasicRemoteRef.java:199) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef.java:542) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.rmi.cluster.ClusterableRemoteRef.invoke(ClusterableRemoteRef.java:313) ~[com.bea.core.weblogic.rmi.client.jar:12.2.1.4]
        at weblogic.jndi.internal.ServerNamingNode_12214_WLStub.lookup(Unknown Source) ~[com.oracle.weblogic.server.stubs.jar:12.2.1.4]
        at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:449) ~[com.oracle.weblogic.jndi.jar:12.2.1.4]
        ... 67 common frames omitted

** Below is the Model.yaml** :
```
domainInfo:
    AdminUserName: '@@SECRET:__weblogic-credentials__:username@@'
    AdminPassword: '@@SECRET:__weblogic-credentials__:password@@'
    ServerStartMode: 'prod'

topology:
    Name: '@@ENV:CUSTOM_DOMAIN_NAME@@'
    AdminServerName: 'admin-server'
    Cluster: 
        'vitality-core-points':
            MulticastTTL: 1
    Server:
        'admin-server':
            ListenPort: 7001
        'm1':
            ListenPort: 8001
            Cluster: 'vitality-core-points'
            Log:
                RedirectStderrToServerLogEnabled: true
                RedirectStdoutToServerLogEnabled: true              
            NetworkAccessPoint:
                T3Channel:
                    Protocol: 't3'
                    PublicAddress: '172.26.108.49'
                    PublicPort: 33413
                    ListenPort: 7999
                    ListenAddress: None
                    HttpEnabledForThisProtocol: true
                    TunnelingEnabled: true
                    OutboundEnabled: false
                    Enabled: true
                    TwoWaySSLEnabled: false
                    ClientCertificateEnforced: false
    Security:
        User:
            system:
                Password: '@@SECRET:vitality-core-points-domain-realm-secret:system@@'
                GroupMemberOf: [  Administrators ]
            vitalityadmin:
                Password: '@@SECRET:vitality-core-points-domain-realm-secret:vitalityadmin@@'
                GroupMemberOf: [  Administrators ]
            capgadmin:
                Password: '@@SECRET:vitality-core-points-domain-realm-secret:capgadmin@@'
                GroupMemberOf: [  Administrators ]
            capgreader:
                Password: '@@SECRET:vitality-core-points-domain-realm-secret:capgreader@@'
                GroupMemberOf: [ Monitors ]

appDeployments:
    Application:
        pointscalc:
            SourcePath: 'wlsdeploy/applications/pointscalc/pointscalc.ear'
            ModuleType: ear
            Target: 'vitality-core-points'
        pointsmanager:
            SourcePath: 'wlsdeploy/applications/pointsmanager/pointsmanager.ear'
            ModuleType: ear
            Target: 'vitality-core-points'       
        statusmanager:
            SourcePath: 'wlsdeploy/applications/statusmanager/statusmanager.ear'
            ModuleType: ear
            Target: 'vitality-core-points'
resources:
  SelfTuning:
    MinThreadsConstraint:
      SampleMinThreads:
        Target: 'vitality-core-points'
        Count: 1
    MaxThreadsConstraint:
      SampleMaxThreads:
        Target: 'vitality-core-points'
        Count: 10
    WorkManager:
      SampleWM:
        Target: 'vitality-core-points'
        MinThreadsConstraint: 'SampleMinThreads'
        MaxThreadsConstraint: 'SampleMaxThreads'`
```
Below are the services 

NAME                                                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                         AGE
vitality-core-points-domain                                NodePort    10.96.68.114   <none>        7999:33413/TCP,8001:34493/TCP   2d23h
vitality-core-points-domain-admin-server                   ClusterIP   None           <none>        7001/TCP                        28d
vitality-core-points-domain-admin-server-ext               NodePort    10.96.119.12   <none>        7001:33411/TCP                  28d
vitality-core-points-domain-cluster-vitality-core-points   ClusterIP   10.96.204.10   <none>        7999/TCP,8001/TCP               3m24s
vitality-core-points-domain-m1                             ClusterIP   None           <none>        7999/TCP,8001/TCP               5d23h
vitality-core-points-domain-m2                             ClusterIP   None           <none>        7999/TCP,8001/TCP               5d23h
vitality-core-points-domain-np                             NodePort    10.96.83.2     <none>        8001:33414/TCP                  2d23h

the public port and service node port are same which is 33413. and the public address is the worker node IP.

Below are my additional questions.

1. Even when we put ListenAddress value as None , the operator always assign the pods service name , why it is so ?
2. Is the default port 8001 is also capible for the T3 communication if yes then I am getting the same error as above when I use defualt port.
3. I tried to give the public address as the service name "vitality-core-points-domain.<namespace-name>" and public port 7999 in model.yaml but problem is still the same.

**Comment by tbarnes-us** [comment]
See https://oracle.github.io/weblogic-kubernetes-operator/faq/external-clients/ -- it covers this specific use case

As for networking/service background, see "user guide".

Note that we can more easily continue the discussion in the slack channel (see "get help" in the doc).

**Comment by robertpatrick** [comment]
@manavtidhan were you able to resolve your issue with the guidance provided by @tbarnes-us?  Please let us know if this is still something that you require help with.

**Comment by manavtidhan** [comment]
HI @robertpatrick : you can close the issue , I was able to connect with T3 channel
