### ISSUE TITLE
wdt discoverDomain.sh failing with unhandled exception

### ISSUE THREAD

**Issue by karntushar** [oracle/weblogic-deploy-tooling#1025]
I am trying to run discoverdomain.sh from WebLogic Deploy Tooling 1.9.18, but its failing with un-handled exception. Seems domain model is not able to extract classpath properly and its failing somewhere. Any fix or suggestions will be helpful.

/home/oracle/tushar/weblogic-deploy/bin/discoverDomain.sh -oracle_home "/scratch/oracle/Oracle/Middleware" -domain_home "/scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube" -archive_file apbuat2.zip -model_file apbuat2.yaml -variable_file apbuat2.properties -admin_user "weblogic" -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001
JDK version is 1.7.0_311-b07
JAVA_HOME = /scratch/oracle/Java/jdk1.7.0_311
WLST_EXT_CLASSPATH = 
CLASSPATH = /home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig 
/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/bin/wlst.sh /home/oracle/tushar/weblogic-deploy/lib/python/discover.py -oracle_home /scratch/oracle/Oracle/Middleware -domain_home /scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube -archive_file apbuat2.zip -model_file apbuat2.yaml -variable_file apbuat2.properties -admin_user weblogic -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001

CLASSPATH=/scratch/oracle/Oracle/Middleware/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Oracle/Middleware/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Java/jdk1.7.0_311/lib/tools.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic_sp.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic.jar:/scratch/oracle/Oracle/Middleware/modules/features/weblogic.server.modules_10.3.6.0.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/webservices.jar:/scratch/oracle/Oracle/Middleware/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/scratch/oracle/Oracle/Middleware/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar:/scratch/oracle/Oracle/Middleware/utils/config/10.3/config-launch.jar::/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbynet.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbyclient.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbytools.jar::

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Jan 8, 2022 11:21:36 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling discoverDomain version is 1.9.18:.d51e628:Nov 04, 2021 21:09 UTC>
Please enter the WebLogic administrator password: 
####<Jan 8, 2022 11:21:40 PM> <INFO> <discover> <main> <WLSDPLY-06025> <Variable file was provided. Model password attributes will be replaced with tokens and corresponding values put into the variable file.>

####<Jan 8, 2022 11:21:42 PM> <INFO> <discover> <_get_domain_name> <WLSDPLY-06022> <Discover domain flexcube>
####<Jan 8, 2022 11:26:15 PM> <INFO> <TopologyDiscoverer> <discover> <WLSDPLY-06600> <Discovering domain model topology>
####<Jan 8, 2022 11:26:16 PM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain AdminConsole>
####<Jan 8, 2022 11:26:16 PM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JMX>
####<Jan 8, 2022 11:26:16 PM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JPA>
####<Jan 8, 2022 11:26:17 PM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JTA>
####<Jan 8, 2022 11:26:17 PM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain Log>
####<Jan 8, 2022 11:26:17 PM> <INFO> <TopologyDiscoverer> <get_clusters> <WLSDPLY-06601> <Discovering 0 clusters>
####<Jan 8, 2022 11:26:18 PM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06603> <Discovering 8 servers>
####<Jan 8, 2022 11:26:18 PM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06604> <Adding Server AdminServer>
####<Jan 8, 2022 11:26:36 PM> <INFO> <Discoverer> <_populate_model_parameters> <WLSDPLY-06154> <Attribute Arguments for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 8, 2022 11:26:36 PM> <INFO> <Discoverer> <_populate_model_parameters> <WLSDPLY-06154> <Attribute ClassPath for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 8, 2022 11:26:38 PM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06604> <Adding Server FCCoreIMPSManagedServer>
Problem invoking WLST - Traceback (innermost last):
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 572, in ?
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 547, in main
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 211, in __discover
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 76, in discover
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 161, in get_servers
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 555, in _discover_subfolders
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 519, in _discover_subfolder
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 394, in _discover_subfolder_with_single_name
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 374, in _discover_subfolder_singleton
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 122, in _populate_model_parameters
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 162, in _add_to_dictionary
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/aliases/aliases.py", line 1027, in get_model_attribute_name_and_value
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 893, in tokenize_classpath
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 858, in tokenize_path
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 54, in fixup_path
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 69, in get_canonical_path
	at java.io.UnixFileSystem.canonicalize0(Native Method)
	at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
	at java.io.File.getCanonicalPath(File.java:624)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

java.io.IOException: java.io.IOException: File name too long

discoverDomain.sh completed but with some issues (exit code = 1)

**Comment by karntushar** [comment]
[discoverDomain_1.19.log](https://github.com/oracle/weblogic-deploy-tooling/files/7833725/discoverDomain_1.19.log)

**Comment by karntushar** [comment]
After using latest version WebLogic Deploy Tooling 1.9.20, still tool is failing with un-handled exception. Please refer below run log. Please help with resolution.
[discoverDomain_13-jan-2022.log](https://github.com/oracle/weblogic-deploy-tooling/files/7859906/discoverDomain_13-jan-2022.log)


[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ /home/oracle/tushar/weblogic-deploy/bin/discoverDomain.sh -oracle_home "/scratch/oracle/Oracle/Middleware" -domain_home "/scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube" -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user "weblogic" -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001
Please set the JAVA_HOME environment variable to point to a Java 7 installation
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ export JAVA_HOME="/scratch/oracle/Java/jdk1.7.0_311"
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ export PATH=$JAVA_HOME/bin:$PATH
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ /home/oracle/tushar/weblogic-deploy/bin/discoverDomain.sh -oracle_home "/scratch/oracle/Oracle/Middleware" -domain_home "/scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube" -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user "weblogic" -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001
JDK version is 1.7.0_311-b07
JAVA_HOME = /scratch/oracle/Java/jdk1.7.0_311
WLST_EXT_CLASSPATH = 
CLASSPATH = /home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig 
/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/bin/wlst.sh /home/oracle/tushar/weblogic-deploy/lib/python/discover.py -oracle_home /scratch/oracle/Oracle/Middleware -domain_home /scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user weblogic -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001

CLASSPATH=/scratch/oracle/Oracle/Middleware/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Oracle/Middleware/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Java/jdk1.7.0_311/lib/tools.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic_sp.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic.jar:/scratch/oracle/Oracle/Middleware/modules/features/weblogic.server.modules_10.3.6.0.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/webservices.jar:/scratch/oracle/Oracle/Middleware/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/scratch/oracle/Oracle/Middleware/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar:/scratch/oracle/Oracle/Middleware/utils/config/10.3/config-launch.jar::/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbynet.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbyclient.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbytools.jar::

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Jan 13, 2022 9:36:00 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling discoverDomain version is 1.9.20:release-1.9.x.54d9dcb:Jan 11, 2022 21:44 UTC>
Please enter the WebLogic administrator password: 
####<Jan 13, 2022 9:36:06 AM> <INFO> <XPathUtil> <getPSU> <> <No patches home at /scratch/oracle/Oracle/Middleware/inventory/patches>
####<Jan 13, 2022 9:36:06 AM> <INFO> <discover> <main> <WLSDPLY-06025> <Variable file was provided. Model password attributes will be replaced with tokens and corresponding values put into the variable file.>

####<Jan 13, 2022 9:36:07 AM> <INFO> <discover> <_get_domain_name> <WLSDPLY-06022> <Discover domain flexcube>
####<Jan 13, 2022 9:40:33 AM> <INFO> <TopologyDiscoverer> <discover> <WLSDPLY-06600> <Discovering domain model topology>
####<Jan 13, 2022 9:40:34 AM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain AdminConsole>
####<Jan 13, 2022 9:40:34 AM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JMX>
####<Jan 13, 2022 9:40:35 AM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JPA>
####<Jan 13, 2022 9:40:35 AM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain JTA>
####<Jan 13, 2022 9:40:35 AM> <INFO> <Discoverer> <discover_domain_mbean> <WLSDPLY-06644> <Adding Domain Log>
####<Jan 13, 2022 9:40:35 AM> <INFO> <TopologyDiscoverer> <get_clusters> <WLSDPLY-06601> <Discovering 0 clusters>
####<Jan 13, 2022 9:40:36 AM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06603> <Discovering 8 servers>
####<Jan 13, 2022 9:40:36 AM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06604> <Adding Server AdminServer>
####<Jan 13, 2022 9:40:53 AM> <INFO> <Discoverer> <_populate_model_parameters> <WLSDPLY-06154> <Attribute Arguments for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 13, 2022 9:40:53 AM> <INFO> <Discoverer> <_populate_model_parameters> <WLSDPLY-06154> <Attribute ClassPath for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 13, 2022 9:40:55 AM> <INFO> <TopologyDiscoverer> <get_servers> <WLSDPLY-06604> <Adding Server FCCoreIMPSManagedServer>
Problem invoking WLST - Traceback (innermost last):
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 572, in ?
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 547, in main
  File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 211, in __discover
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 77, in discover
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 162, in get_servers
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 555, in _discover_subfolders
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 519, in _discover_subfolder
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 394, in _discover_subfolder_with_single_name
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 374, in _discover_subfolder_singleton
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 122, in _populate_model_parameters
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 162, in _add_to_dictionary
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/aliases/aliases.py", line 1025, in get_model_attribute_name_and_value
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 901, in tokenize_classpath
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 866, in tokenize_path
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 54, in fixup_path
  File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 69, in get_canonical_path
	at java.io.UnixFileSystem.canonicalize0(Native Method)
	at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
	at java.io.File.getCanonicalPath(File.java:624)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

java.io.IOException: java.io.IOException: File name too long


discoverDomain.sh completed but with some issues (exit code = 1)
[discoverDomain_13-jan-2022.log](https://github.com/oracle/weblogic-deploy-tooling/files/7859899/discoverDomain_13-jan-2022.log)

**Comment by rakillen** [comment]
This fix is not included in WDT 1.9.20, but will be in the next release, probably WDT 2.0.
