### ISSUE TITLE
discoverDomain.sh failing during classpath extraction

### ISSUE THREAD

**Issue by karntushar** [oracle/weblogic-deploy-tooling#1033]
After using latest version **WebLogic Deploy Tooling 1.9.20**, still tool is failing with un-handled exception. Please refer below run log. Please help with resolution.

[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ /home/oracle/tushar/weblogic-deploy/bin/discoverDomain.sh -oracle_home "/scratch/oracle/Oracle/Middleware" -domain_home "/scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube" -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user "weblogic" -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001
Please set the JAVA_HOME environment variable to point to a Java 7 installation
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ export JAVA_HOME="/scratch/oracle/Java/jdk1.7.0_311"
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ export PATH=$JAVA_HOME/bin:$PATH
[oracle@P1APB-TVL-FLX16 weblogic-deploy]$ /home/oracle/tushar/weblogic-deploy/bin/discoverDomain.sh -oracle_home "/scratch/oracle/Oracle/Middleware" -domain_home "/scratch/oracle/Oracle/Middleware/user_projects/
[discoverDomain_13-jan-2022.log](https://github.com/oracle/weblogic-deploy-tooling/files/7859927/discoverDomain_13-jan-2022.log)
domains/flexcube" -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user "weblogic" -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001
JDK version is 1.7.0_311-b07
JAVA_HOME = /scratch/oracle/Java/jdk1.7.0_311
WLST_EXT_CLASSPATH =
CLASSPATH = /home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig
/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/bin/wlst.sh /home/oracle/tushar/weblogic-deploy/lib/python/discover.py -oracle_home /scratch/oracle/Oracle/Middleware -domain_home /scratch/oracle/Oracle/Middleware/user_projects/domains/flexcube -archive_file apbuat4.zip -model_file apbuat4.yaml -variable_file apbuat4.properties -admin_user weblogic -admin_url t3://P1APB-TVL-FLX16.india.airtel.itm:8001

CLASSPATH=/scratch/oracle/Oracle/Middleware/patch_wls1036/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Oracle/Middleware/patch_ocp371/profiles/default/sys_manifest_classpath/weblogic_patch.jar:/scratch/oracle/Java/jdk1.7.0_311/lib/tools.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic_sp.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/weblogic.jar:/scratch/oracle/Oracle/Middleware/modules/features/weblogic.server.modules_10.3.6.0.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/server/lib/webservices.jar:/scratch/oracle/Oracle/Middleware/modules/org.apache.ant_1.7.1/lib/ant-all.jar:/scratch/oracle/Oracle/Middleware/modules/net.sf.antcontrib_1.1.0.0_1-0b2/lib/ant-contrib.jar:/home/oracle/tushar/weblogic-deploy/lib/weblogic-deploy-core.jar:/scratch/oracle/Oracle/Middleware/utils/config/10.3/config-launch.jar::/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbynet.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbyclient.jar:/scratch/oracle/Oracle/Middleware/wlserver_10.3/common/derby/lib/derbytools.jar::

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Jan 13, 2022 9:36:00 AM> <The WebLogic Deploy Tooling discoverDomain version is 1.9.20:release-1.9.x.54d9dcb:Jan 11, 2022 21:44 UTC>
Please enter the WebLogic administrator password:
####<Jan 13, 2022 9:36:06 AM> <> <No patches home at /scratch/oracle/Oracle/Middleware/inventory/patches>
####<Jan 13, 2022 9:36:06 AM>

####<Jan 13, 2022 9:36:07 AM> <_get_domain_name>
####<Jan 13, 2022 9:40:33 AM>
####<Jan 13, 2022 9:40:34 AM> <discover_domain_mbean>
####<Jan 13, 2022 9:40:34 AM> <discover_domain_mbean>
####<Jan 13, 2022 9:40:35 AM> <discover_domain_mbean>
####<Jan 13, 2022 9:40:35 AM> <discover_domain_mbean>
####<Jan 13, 2022 9:40:35 AM> <discover_domain_mbean>
####<Jan 13, 2022 9:40:35 AM> <get_clusters> <Discovering 0 clusters>
####<Jan 13, 2022 9:40:36 AM> <get_servers> <Discovering 8 servers>
####<Jan 13, 2022 9:40:36 AM> <get_servers>
####<Jan 13, 2022 9:40:53 AM> <_populate_model_parameters> <Attribute Arguments for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 13, 2022 9:40:53 AM> <_populate_model_parameters> <Attribute ClassPath for model folder at location /Server/ServerStart is not in the lsa map and is not defined with get to retrieve the attribute value>
####<Jan 13, 2022 9:40:55 AM> <get_servers>
Problem invoking WLST - Traceback (innermost last):
File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 572, in ?
File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 547, in main
File "/home/oracle/tushar/weblogic-deploy/lib/python/discover.py", line 211, in __discover
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 77, in discover
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 162, in get_servers
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 555, in _discover_subfolders
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 519, in _discover_subfolder
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 394, in _discover_subfolder_with_single_name
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 374, in _discover_subfolder_singleton
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 122, in _populate_model_parameters
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 162, in _add_to_dictionary
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/aliases/aliases.py", line 1025, in get_model_attribute_name_and_value
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 901, in tokenize_classpath
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/model_context.py", line 866, in tokenize_path
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 54, in fixup_path
File "/home/oracle/tushar/weblogic-deploy/lib/python/wlsdeploy/util/path_utils.py", line 69, in get_canonical_path
at java.io.UnixFileSystem.canonicalize0(Native Method)
at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
at java.io.File.getCanonicalPath(File.java:624)
at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)

java.io.IOException: java.io.IOException: File name too long

discoverDomain.sh completed but with some issues (exit code = 1)

**Comment by karntushar** [comment]
Issue linked to issue-#1025-split-classpath

**Comment by rakillen** [comment]
This fix is not included in WDT 1.9.20, but will be in the next release, probably WDT 2.0.

**Comment by robertpatrick** [comment]
@karntushar correct, this is only fixed in `main` and will be part of the WDT 2.0.0 release later this month.  If you need the fix sooner, feel free to build your own interim installer from main.
