### ISSUE TITLE
WebLogic version for aliases isn't a number

### ISSUE THREAD

**Issue by jesusploitx** [oracle/weblogic-deploy-tooling#1088]
Hi,
We have Oracle Service Bus, 12.2.1.3.0.1425 version. We applied the patch "WLS PATCH SET UPDATE 12.2.1.3.0(ID:191217.1425)".
The issue is when we launch discoverDomain script, so WebLogic version isn't a number because it adds a parenthesis to the version number (  12.2.1.3.0.**1425)**  ).

How does WDT get the alias for the version?
Is it possible to skip the validation that the alias is not a number or what options would there be?

The log is:

JDK version is 1.8.0_211-b12
JAVA_HOME = /mdw/oracle/java/
WLST_EXT_CLASSPATH = /mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/weblogic-deploy-core.jar
CLASSPATH = /mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig
/mdw/oracle/mid12213osb/oracle_common/common/bin/wlst.sh /mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/discover.py -oracle_home /mdw/oracle/mid12213osb -domain_home /mdw/oracle/domains/osbmdwdev -archive_file /home/oracle/wdt/discover_wzgdcvbpel001dv.zip -model_file /home/oracle/wdt/discover_wzgdcvbpel001dv.yaml -variable_file /home/oracle/wdt/discover_wzgdcvbpel001dv.properties

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Feb 11, 2022 11:47:22 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling discoverDomain version is 2.0.0:.2d965e1:Jan 27, 2022 15:23 UTC>
####<Feb 11, 2022 11:47:22 AM> <INFO> <ModelContext> <__copy_from_args> <WLSDPLY-01050> <WebLogic version for aliases is 12.2.1.3.0.1425)>
####<Feb 11, 2022 11:47:22 AM> <INFO> <discover> <main> <WLSDPLY-06025> <Variable file was provided. Model password attributes will be replaced with tokens and corresponding values put into the variable file.>
####<Feb 11, 2022 11:47:42 AM> <INFO> <discover> <_get_domain_name> <WLSDPLY-06022> <Discover domain osbmdwdev>
####<Feb 11, 2022 11:48:18 AM> <INFO> <TopologyDiscoverer> <discover> <WLSDPLY-06600> <Discovering domain model topology>
Problem invoking WLST - Traceback (innermost last):
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/discover.py", line 567, in ?
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/discover.py", line 542, in main
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/discover.py", line 211, in __discover
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 73, in discover
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 305, in discover_domain_parameters
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/tool/discover/discoverer.py", line 94, in _populate_model_parameters
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/aliases.py", line 197, in get_wlst_attributes_path
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 395, in get_wlst_attribute_path_for_location
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1576, in _AliasEntries__get_path_for_location
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1005, in _AliasEntries__get_dictionary_for_location
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1040, in _AliasEntries__get_category_dictionary
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1061, in _AliasEntries__load_category
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1238, in _AliasEntries__apply_wlst_context_changes
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1415, in _AliasEntries__resolve_attribute_by_wlst_context
  File "/mdw/oracle/wdt/weblogic-deploy_2.0.0/lib/python/wlsdeploy/aliases/alias_entries.py", line 1458, in _AliasEntries__version_in_range
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at oracle.weblogic.deploy.aliases.VersionUtils.compareVersions(VersionUtils.java:104)
        at oracle.weblogic.deploy.aliases.VersionUtils.isVersionInRange(VersionUtils.java:178)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.NumberFormatException: java.lang.NumberFormatException: For input string: "1425)"

discoverDomain.sh completed but with some issues (exit code = 1)

**Comment by ddsharpe** [comment]
We will look into this, looks like a bug.  The code is looking at the patches applied to see if there was a PSU applied.  The XPath and location code was submitted as part of PR #992

**Comment by jesuspeon** [comment]
A workaround is to modify the description attribute by removing the last parenthesis in the file **_ORACLE_HOME_**/inventory/patches/30675853.xml

**Comment by ddsharpe** [comment]
Fixed in #1093, and available in the next release.
