### ISSUE TITLE
unable to run WDT in online mode - getting java.lang.NullPointerException

### ISSUE THREAD

**Issue by dhayanands** [oracle/weblogic-deploy-tooling#1126]
I am trying to run WDT in online mode to get IDCS related configuration but it fails with below error

```
####<May 16, 2022 11:34:03 AM> <INFO> <TopologyDiscoverer> <discover> <WLSDPLY-06600> <Discovering domain model topology>
Traceback (most recent call last):
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 562, in <module>
    main(sys.argv)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 537, in main
    model = __discover(model_context, aliases, credential_injector, helper)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 537, in main
    model = __discover(model_context, aliases, credential_injector, helper)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 212, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 212, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 73, in discover
    self.discover_domain_parameters()
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 304, in discover_domain_parameters
    self._populate_model_parameters(self._dictionary, location)
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 119, in _populate_model_parameters
    if not self._wlst_helper.is_set(wlst_lsa_param):
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py", line 121, in is_set
    result = mbean.isSet(attribute)
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py", line 121, in is_set
    result = mbean.isSet(attribute)
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at weblogic.utils.StackTraceDisabled.unknownMethod()
Caused by: java.lang.reflect.InvocationTargetException
        ... 1 more
Caused by: java.lang.NullPointerException
        ... 1 more
java.lang.AssertionError: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
Problem invoking WLST - Traceback (most recent call last):
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 562, in <module>
    main(sys.argv)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 537, in main
    model = __discover(model_context, aliases, credential_injector, helper)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 537, in main
    model = __discover(model_context, aliases, credential_injector, helper)
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 212, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "/home/oracle/weblogic-deploy/lib/python/discover.py", line 212, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 73, in discover
    self.discover_domain_parameters()
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 304, in discover_domain_parameters
    self._populate_model_parameters(self._dictionary, location)
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 119, in _populate_model_parameters
    if not self._wlst_helper.is_set(wlst_lsa_param):
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py", line 121, in is_set
    result = mbean.isSet(attribute)
  File "/home/oracle/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py", line 121, in is_set
    result = mbean.isSet(attribute)
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at weblogic.utils.StackTraceDisabled.unknownMethod()
Caused by: java.lang.reflect.InvocationTargetException
        ... 1 more
Caused by: java.lang.NullPointerException
        ... 1 more
java.lang.AssertionError: java.lang.AssertionError: java.lang.reflect.InvocationTargetException


discoverDomain.sh completed but with some issues (exit code = 1)

```

The WebLogic server is of version : 14.1.1.0.0 and is created from OCI market place. attaching the log herewith.

WDT version is 2.2.0

[discoverDomain.log](https://github.com/oracle/weblogic-deploy-tooling/files/8699667/discoverDomain.log)

**Comment by dhayanands** [comment]
when i run it offline, i get the below error and as i understand to get the idcs related configuration, I need to run it in online mode

```
####<May 16, 2022 11:24:53 AM> <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain WeblogicTest_domain at /u01/data/domains/WeblogicTest_domain : Failed to get the WLST attributes path for location (model_folders = ['SecurityConfiguration', 'Realm', 'AuthenticationProvider', 'OracleIdentityCloudIntegrator'],  'name_tokens' = {'DOMAIN': 'WeblogicTest_domain','REALM': 'myrealm','PROVIDER': 'IDCSIntegrator','SECURITYCONFIGURATION': 'WeblogicTest_domain'}): Alias folder OracleIdentityCloudIntegrator does not exist at path /SecurityConfiguration/Realm/AuthenticationProvider>
```

**Comment by CarolynRountree** [comment]
Could you provide the discoverDomain.log from the directory ./weblogic-deploy/logs

**Comment by robertpatrick** [comment]
@dhayanands Please provide the complete WDT log file and model file(s) used to produce this issue.

**Comment by dhayanands** [comment]
@robertpatrick this error occurred when i tried to discover the domain to generate a model file.

**Comment by robertpatrick** [comment]
@dhayanands Please zip up the domain directory and send it to us.

**Comment by dhayanands** [comment]
@robertpatrick I am sorry as it will have customer related info and it will be hard to share.

**Comment by dhayanands** [comment]
@rakillen thank you! that is an awesome news :)
