### ISSUE TITLE
Remote discoverDomain erroring out

### ISSUE THREAD

**Issue by WhatDoor** [oracle/weblogic-deploy-tooling#1446]
Here is the output when I try to run the discover domain. 

```
####<Apr 11, 2023 4:10:26 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application MSMQAdapter>
####<Apr 11, 2023 4:10:26 PM> <TODO> <PyReflectedFunction> <__call__> <WLSDPLY-06041> <Please collect the APPLICATION from the remote file system location /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/@@ORACLE_HOME@@/soa/soa/connectors/MSMQAdapter.rar and place it into the archive file at wlsdeploy/applications/MSMQAdapter.rar.>
####<Apr 11, 2023 4:10:27 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application OracleAppsAdapter>
####<Apr 11, 2023 4:10:28 PM> <TODO> <PyReflectedFunction> <__call__> <WLSDPLY-06041> <Please collect the APPLICATION from the remote file system location /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/@@ORACLE_HOME@@/soa/soa/connectors/AppsAdapter.rar and place it into the archive file at wlsdeploy/applications/AppsAdapter.rar.>
####<Apr 11, 2023 4:10:29 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application OracleBamAdapter>
####<Apr 11, 2023 4:10:30 PM> <TODO> <PyReflectedFunction> <__call__> <WLSDPLY-06041> <Please collect the APPLICATION from the remote file system location /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/@@ORACLE_HOME@@/soa/soa/connectors/OracleBamAdapter.rar and place it into the archive file at wlsdeploy/applications/OracleBamAdapter.rar.>
####<Apr 11, 2023 4:10:31 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application SAPAdapter>
####<Apr 11, 2023 4:10:31 PM> <TODO> <PyReflectedFunction> <__call__> <WLSDPLY-06041> <Please collect the APPLICATION from the remote file system location /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/@@ORACLE_HOME@@/soa/soa/connectors/SAPAdapter.rar and place it into the archive file at wlsdeploy/applications/SAPAdapter.rar.>
####<Apr 11, 2023 4:10:32 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc>
####<Apr 11, 2023 4:10:33 PM> <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain ent_soa_sit_domain at /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/ : WLSDPLY-06404>

Issue Log for discoverDomain version 3.1.0 running WebLogic version 12.2.1.4.0 online mode:

SEVERE Messages:

        1. WLSDPLY-06011: discoverDomain failed to discover domain ent_soa_sit_domain at /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/ : WLSDPLY-06404

Total:   SEVERE :    1  WARNING :    0
```

And when I check the log file, I can see this
```
####<Apr 14, 2023 1:48:28 PM> <INFO> <DeploymentsDiscoverer> <get_applications> <WLSDPLY-06392> <Adding Application SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc>
####<Apr 14, 2023 1:48:28 PM> <FINER> <Discoverer> <_populate_model_parameters> <WLSDPLY-06100> <Find attributes at location /AppDeployments/SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc>
####<Apr 14, 2023 1:48:28 PM> <FINER> <WlstHelper> <lsa> <> <THROW
oracle.weblogic.deploy.discover.DiscoverException: WLSDPLY-00029: ls(/AppDeployments/SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc, returnType=a, returnMap=true) in online mode failed: Error occurred while performing ls : Error while retrieving attribute names and values : javax.management.RuntimeMBeanException: MBean getAttribute failed: java.lang.IllegalArgumentException: /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/servers/AdminServer/stage/SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc/plan/SB_JMS_Proxy_N53e9b6a4.N251cc8fd.1.18755024714.N7ffc_Plan.xml (No such file or directory)

…

####<Apr 14, 2023 1:48:28 PM> <FINER> <DeploymentsDiscoverer> <is_structured_app> <> <ENTRY {'Target': 'osb_cluster'}>
####<Apr 14, 2023 1:48:28 PM> <FINER> <DeploymentsDiscoverer> <is_structured_app> <> <THROW
oracle.weblogic.deploy.discover.DiscoverException: WLSDPLY-06404
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)

…

####<Apr 14, 2023 1:48:28 PM> <SEVERE> <discover> <main> <WLSDPLY-06011> <discoverDomain failed to discover domain ent_soa_sit_domain at /u01/app/oracle/admin/ent_soa_sit_domain/aserver/ent_soa_sit_domain/ : WLSDPLY-06404
oracle.weblogic.deploy.discover.DiscoverException: WLSDPLY-06404
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

**Comment by WhatDoor** [comment]
Not really sure why this is occuring

**Comment by robertpatrick** [comment]
@WhatDoor can we start by you showing us the entire WDT discoverDomain.log file?

**Comment by jshum2479** [comment]
@WhatDoor   WDT does not officially support discovering OSB domains,  the closest one is a JRF domain, but you can also extend the type of domain supported by WDT by creating your own typedef json file.   See for details here:

https://oracle.github.io/weblogic-deploy-tooling/userguide/tools-config/domain_def/

You can use this as a starting point,  lots of default resources discovered in the model are coming from out-of-the-box OSB templates and will not be of much use for creating a new domain out of it.


Another issue is OSB generates MDB for the JMS proxy (if you use SOA jms adapter you won't have this problem).  The generated app has the name pattern `SB_JMS_Proxy_xxxx`   this is under the `$DOMAIN_HOME/sbgen`  directory.    Since this is generated app and managed by the service bus, and it should not be manipulated directly,  so you should skip this app in the typedef definition.   For example,

```
"system-elements": {
        "apps": [
            . . .
            "^SB_JMS_Proxy_*"
        ],
 ```  
 
 I don't remember there are any other generated apps, but if there are any, you can use the same pattern.
