### ISSUE TITLE
WDT3: Error occurred in "OPSS Processing" phase execution

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#1499]
We are using WDT for  domain config of  MW components (OAM, OHS, OSB, SOA, ...)  
Currently, we are working on upgrading `WDT` from `1.9.20` to `3.2.5` (the latest version)    

The flow we follow is simply;  
- ensure `rcu schemas` are setup using oracle's `rcu` utility, each schema has a unique pwd  
- domain config (`createDomain`) using `WDT` by feeding it with `WDT templates` 

While applying this for OAM domain, I get an error at `createDomain` phase.  
NB! this works fine when using `WDT 1.9.20` and this error happens only when using the `WDT 3.x.x`  

```
...
####<Oct 6, 2023 10:17:09 AM> <FINER> <DomainCreator> <__apply_base_domain_config> <> <RETURN>
####<Oct 6, 2023 10:17:09 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12205> <Writing base domain elhoam_domain to directory /u01/elhoam/domain/elhoam_domain>
####<Oct 6, 2023 10:17:09 AM> <FINER> <WlstHelper> <write_domain> <> <ENTRY /u01/elhoam/domain/elhoam_domain>
####<Oct 6, 2023 10:17:18 AM> <FINER> <WlstHelper> <write_domain> <> <THROW
oracle.weblogic.deploy.create.CreateException: WLSDPLY-00044: writeDomain(/u01/elhoam/domain/elhoam_domain) failed : Error writing domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: oracle.security.opss.tools.lifecycle.LifecycleException: JDBC password for opss-audit-DBDS is missing for configuring security store to database.
64254: Check log for more detail.
null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_create_exception$4(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:102)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at org.python.core.PyObject._callextra(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_exception$2(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:74)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at wlsdeploy.tool.util.wlst_helper$py.write_domain$38(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:764)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:199)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
 ...  
        at wlsdeploy.tool.create.domain_creator$py._DomainCreator__extend_domain_with_select_template$18(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py:661)
        at wlsdeploy.tool.create.domain_creator$py.call_function(/u01/binaries/elhoam/wdt/3.2.5/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
...
        at weblogic.management.scripting.WLST.main(WLST.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at weblogic.WLST.main(WLST.java:47)
Caused by: com.oracle.cie.domain.script.jython.WLSTException: Error writing domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: oracle.security.opss.tools.lifecycle.LifecycleException: JDBC password for opss-audit-DBDS is missing for configuring security store to database.
64254: Check log for more detail.
null
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
        at sun.reflect.GeneratedMethodAccessor800.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

If needed, I can also send the full `createDomain.log`  

Please kindly advise, your feedback is much appreciated

Regards
Yilmaz

**Comment by robertpatrick** [comment]
@zeusbaba In order to support RCU schemas where every Data Source has a different password, you will need to create a sparse DataSource configuration that specifies the password for each RCU DataSource.

**Comment by jshum2479** [comment]
@zeusbaba   We no longer use the shadow table to retrieve database connection/credentials information to set up the datasources.  Since you are using different credentials for each datasource, you can create a sparse model and specify their passwords.

https://oracle.github.io/weblogic-deploy-tooling/userguide/database/connect-db/

Look for Default template data source section.

**Comment by zeusbaba** [comment]
Thanks for feedback.  
We already are using WDT template for `datasources`.  
we split tempaltes into context groups, e.g. `JDBC, JMS, baseline, etc`.  

see snippet from template for `JDBCSystemResource`  
```
resources:
  JDBCSystemResource:
    'opss-data-source':
        Target: 'elhoam_cluster,AdminServer'
        JdbcResource:
            JDBCConnectionPoolParams:
                MaxCapacity: 25
                ShrinkFrequencySeconds: 900
                MinCapacity: 2
                StatementCacheSize: 10
            JDBCDataSourceParams:
                GlobalTransactionsProtocol: None
                JNDIName: jdbc/OpssDataSource
            JDBCDriverParams:
                URL: '....redacted...'
```

**Comment by zeusbaba** [comment]
as I stated in the original post, the same setup with the same WDT templates works fine with `v1.9.20` but fails with `v3.2.5`

**Comment by robertpatrick** [comment]
As Johnny mentioned, we changed our approach to handling RCU-related Data Sources to not use the STB table to populate that connection-related information (primarily due to RCU limitations for database connection URLs).  The STB table approach was handling your specific use case in WDT 1.x.

The template approach works fine in our tests so clearly, there is something different between what you are doing and what we test.  Can you provide a simplified set of steps and model files that will allow us to reproduce the issue?

**Comment by zeusbaba** [comment]
with 'template approach', do you mean that _only_  `datasources` is sufficient?  
don't we need to define `RCUDbInfo:`  anymore?  

btw, as you requested, i'm preparing template to share, i need to clean out customer related data, sharing soon,

**Comment by zeusbaba** [comment]
here are the steps:  

step1) create `rcu schemas` using oracle's `rcu util`  
```
        rcu_components: [
          "IAU", "IAU_APPEND", "IAU_VIEWER",
          "OAM", "MDS", "OPSS",
          "STB", "WLS"
        ]
```  

step2) configure OAM domain ( `createDomain`) using `WDT templates`   
[here is the snippet](https://gist.github.com/zeusbaba/a7fcb2920e64dfc02222af8d4602a3f5) for `JDBCSystemResource:`   
it contains each of `datasources` corresponding to `rcu schemas`

**Comment by robertpatrick** [comment]
@zeusbaba Thanks, we have managed to identify an issue so Johnny is working to try to understand what needs to be done to correct the problem.  Once we identify a fix, it would be good if we could send you an installer to test to make sure that it resolves your issue prior to releasing a new version.

**Comment by zeusbaba** [comment]
thanks @robertpatrick  & @jshum2479  
Happy to hear that you / your team has found a solution so fast :)  

sure, i'll do a quick round of testing now, i'll get back to you with results soon

**Comment by zeusbaba** [comment]
few lines from  `createDomain.log` 
```
####<Oct 10, 2023 5:04:06 PM> <FINER> <WlstHelper> <write_domain> <> <THROW
oracle.weblogic.deploy.create.CreateException: WLSDPLY-00044: writeDomain(/u01/elhoam/domain/elhoam_domain) failed : Error writing domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: oracle.security.opss.tools.lifecycle.LifecycleException: JDBC password for opss-audit-DBDS is missing for configuring security store to database.
64254: Check log for more detail.
null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_create_exception$4(/u01/binaries/elhoam/wdt/fix_10okt23/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:102)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/fix_10okt23/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at org.python.core.PyObject._callextra(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_exception$2(/u01/binaries/elhoam/wdt/fix_10okt23/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:74)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/fix_10okt23/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
...
Caused by: com.oracle.cie.domain.script.jython.WLSTException: Error writing domain:
64254: Error occurred in "OPSS Processing" phase execution
64254: Encountered error: oracle.security.opss.tools.lifecycle.LifecycleException: JDBC password for opss-audit-DBDS is missing for configuring security store to database.
64254: Check log for more detail.
null
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
        at sun.reflect.GeneratedMethodAccessor834.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.python.core.PyReflectedFunction.__call__(Unknown Source)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyInstance.invoke(Unknown Source)
        at org.python.pycode._pyx5.command$1(/tmp/WLSTOfflineIni4737292384558188252.py:19)
        at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni4737292384558188252.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:184)
        at org.python.pycode._pyx5.writeDomain$28(/tmp/WLSTOfflineIni4737292384558188252.py:111)
        at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni4737292384558188252.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:181)
        at wlsdeploy.tool.util.wlst_helper$py.write_domain$38(/u01/binaries/elhoam/wdt/fix_10okt23/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:762)
        ... 59 more
```

**Comment by jshum2479** [comment]
I use model like this

```
    RCUDbInfo:
       rcu_prefix: FMW
       rcu_schema_password: 
       rcu_db_conn_string: 
topology:
    Name: 'sample-domain1'
    AdminServerName: "admin-server"
    ProductionModeEnabled: 'true'
    Cluster:
        "cluster-1":
    Server:
        "admin-server":
            ListenPort: 7001
        "ms1":
            ListenPort: 8001
            Cluster: 'cluster-1'
resources:
   JDBCSystemResource:
        WLSSchemaDataSource:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
        LocalSvcTblDataSource:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
        opss-data-source:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
        opss-audit-viewDS:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
        opss-audit-DBDS:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
        mds-owsm:
            JdbcResource:
                JDBCDriverParams:
                    PasswordEncrypted: 
```

**Comment by jshum2479** [comment]
Note:  we don't support using with `-run_rcu`. to create schemas with different credentials for different schemas

**Comment by zeusbaba** [comment]
yes, we don't use `-run_rcu` either, `rcu schemas` are created separately (see original post).  

as I understand (see from your example); regardless of WDT version, `RCUDbInfo` is still needed  
```
domainInfo:
    RCUDbInfo:
        rcu_prefix: 'ELHOAM'
        rcu_db_conn_string: 'elhdb-...'
        rcu_schema_password: '...  
```  
which I already do, and still get the same error as result.

**Comment by jshum2479** [comment]
Do you have the resources section setting the different passwords?

**Comment by zeusbaba** [comment]
yes, see [gist snippet](https://gist.github.com/zeusbaba/a7fcb2920e64dfc02222af8d4602a3f5) shared in [this comment](https://github.com/oracle/weblogic-deploy-tooling/issues/1499#issuecomment-1755689963)

**Comment by jshum2479** [comment]
Can you share the standard output log including the command line argument and the createDomain.log?

**Comment by zeusbaba** [comment]
here is the ansible task remotely executing `createDomain.sh` 
```
- name: createDomain using WDT template
  command: >
    {{ wdt_home }}/bin/createDomain.sh
    -oracle_home {{ mw_home }}
    -domain_type OAM
    -domain_parent {{ domain_root }}
    -model_file {{ wdt_templates | join(',') }}
  args:
    chdir: "{{ wdt_templates_home }}"
  environment:
    ELHUB_ENVIRONMENT: "{{ eltostratus_env }}"
    JAVA_HOME: "{{ java_home }}"

```
i've shared `createDomain.log` via email

**Comment by jshum2479** [comment]
I don't see in the log trying to configure the infra db.  

```
####<Oct 10, 2023 5:03:52 PM> <FINER> <DomainCreator> <__configure_fmw_infra_database> <WLSDPLY-12249> <Domain typedef has no RCU schema dependencies, skipping database configuration>
```

Since you are creating your own typedefs.  Can you attach you OAM.json typedefs file?

**Comment by zeusbaba** [comment]
yes `OAM.json` is a custom `typedef`, it contains OAM specific extension.  
see definition here  
```
"OAM_12c": {
      "baseTemplate": "Basic WebLogic Server Domain",
      "extensionTemplates": [
        "Oracle Access Management Suite",
        "Oracle JRF WebServices Asynchronous services"
      ],
      "rcuSchemas": []
    }
```

**Comment by jshum2479** [comment]
Our logic depends on that, so you should put list out the schemas there.

**Comment by zeusbaba** [comment]
i see, this is introduced with `v3.x` i assume?  
sure, i'll do another round now.  
using the binaries you sent, and including `rcu` list in `typedef`  
i'll share results soon

**Comment by jshum2479** [comment]
I make a minor change, can you use this instead.

[weblogic-deploy.zip](https://github.com/oracle/weblogic-deploy-tooling/files/12860658/weblogic-deploy.zip)

**Comment by zeusbaba** [comment]
strange that it fails with `oamDS` this time???
```  
"####<Oct 10, 2023 6:34:31 PM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09608> <Updating JDBCSystemResource oamDS>",
        "",
        "Issue Log for createDomain version 3.2.6-SNAPSHOT running WebLogic version 12.2.1.4.0.230702 offline mode:",
        "",
        "SEVERE Messages:",
        "",
        "        1. WLSDPLY-12410: createDomain failed to deploy the resources and applications to the domain: Failed to set attribute Target in path /JDBCSystemResource/oamDS to value AdminServer,oam_policy_mgr1,oam_server1,elhoam_cluster: wrong type",
        " @com.oracle.cie.domain.operation.config.VDomainConfig.createSimpleAspects(VDomainConfig.java:73)",
```

why it tries to wrong target? `oam_policy_mgr1` doesn't exist in our setup  
```
WLSDPLY-0100: Failed to set attribute Target in path /JDBCSystemResource/oamDS to value AdminServer,oam_policy_mgr1,oam_server1,elhoam_cluster: wrong type
```

**Comment by zeusbaba** [comment]
```
####<Oct 10, 2023 6:34:31 PM> <FINER> <deployer_utils> <create_and_cd> <> <RETURN /JDBCSystemResource/oamDS>
####<Oct 10, 2023 6:34:31 PM> <FINER> <DatasourceDeployer> <get_location_type> <> <ENTRY model_folders = ['JDBCSystemResource'],  'name_tokens' = {'DATASOURCE': 'oamDS'}>
####<Oct 10, 2023 6:34:31 PM> <FINER> <AttributeSetter> <__merge_existing_items> <> <ENTRY elhoam_cluster,AdminServer ['AdminServer', 'oam_policy_mgr1', 'oam_server1']>
####<Oct 10, 2023 6:34:31 PM> <FINER> <AttributeSetter> <set_attribute> <WLSDPLY-19211> <Setting attribute Target with model value AdminServer,oam_policy_mgr1,oam_server1,elhoam_cluster to value AdminServer,oam_policy_mgr1,oam_server1,elhoam_cluster in location /JDBCSystemResource>
####<Oct 10, 2023 6:34:31 PM> <FINER> <WlstHelper> <set> <> <THROW
oracle.weblogic.deploy.deploy.DeployException: WLSDPLY-0100: Failed to set attribute Target in path /JDBCSystemResource/oamDS to value AdminServer,oam_policy_mgr1,oam_server1,elhoam_cluster: wrong type
 @com.oracle.cie.domain.operation.config.VDomainConfig.createSimpleAspects(VDomainConfig.java:73)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_deploy_exception$5(/u01/binaries/elhoam/wdt/fix/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:128)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/fix/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at org.python.core.PyObject._callextra(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_exception$2(/u01/binaries/elhoam/wdt/fix/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:74)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhoam/wdt/fix/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
```

**Comment by zeusbaba** [comment]
see WDT template from our `datasources`   
```
    oamDS:
      Target: 'elhoam_cluster,AdminServer'
      JdbcResource:
        JDBCConnectionPoolParams:
          MaxCapacity: 400
          InactiveConnectionTimeoutSeconds: 300
          ShrinkFrequencySeconds: 0
          MinCapacity: 50
          StatementCacheSize: 0
          InitialCapacity: 20
          TestTableName: SQL SELECT 1 FROM DUAL
          TestFrequencySeconds: 0
          TestConnectionsOnReserve: true
          SecondsToTrustAnIdlePoolConnection: 0
          ConnectionCreationRetryFrequencySeconds: 10
        JDBCDataSourceParams:
          JNDIName: jdbc/oamds
        JDBCDriverParams:
          PasswordEncrypted: '....'
          DriverName: oracle.jdbc.OracleDriver
          URL: 'jdbc:oracle:thin:...'
          Properties:
            databasename:
              Value: oamDS
            logintimeout:
            oracle.net.CONNECT_TIMEOUT:
              Value: 10000
            servername:
              Value: '...'
            user:
              Value: 'ELHOAM_OAM'
```

**Comment by jshum2479** [comment]
Oh I see the problem.  I do the reset before the topology is created, so set targets failed.   Can you try this again. I don't have an easy way to test OAM.

[weblogic-deploy.zip](https://github.com/oracle/weblogic-deploy-tooling/files/12861819/weblogic-deploy.zip)

**Comment by jshum2479** [comment]
You should also consider changing your custom typedefs to set the `serverGroupToTargets` and `dynamicClusterServerGroupsToTarget`,  check the JRF.json for syntax.  I don't know the details for OAM but usually you can get that if you are using the graphical config wizard.   That way your sparse jdbc part of the model only have to override what you need and no need to provide the whole portion,  the template should have all the common attributes set.  We use the information in RCUDbinfo for the default connection information where all schemas use, and then the sparse model can be used as an override if needed.

**Comment by robertpatrick** [comment]
My suggestion is we focus on making the JRF domain creation work properly.  WDT does not officially support OAM so once the JRF use case is working, you should be able to use a valid typedef file for OAM and have it work properly.  

What fields are needed in the typedef file to create a domain with RCU schemas has not changed.  I suppose it is possible that WDT 1.9.x might have been more tolerant of typedef file errors but that doesn't constitute a regression in my mind.

**Comment by zeusbaba** [comment]
Thanks for your efforts so far.  I will be back later and continue on this collaboration. 

p.s. i'm based in Oslo, i'll try to be online in sync with your timezone.

**Comment by zeusbaba** [comment]
> Oh I see the problem. I do the reset before the topology is created, so set targets failed. Can you try this again. I don't have an easy way to test OAM.
> 
> [weblogic-deploy.zip](https://github.com/oracle/weblogic-deploy-tooling/files/12861819/weblogic-deploy.zip)

good news @jshum2479 :) 
this version worked fine and created domain successfully 🥇  

```
"Issue Log for createDomain version 3.2.6-SNAPSHOT running WebLogic version 12.2.1.4.0.230702 offline mode:",
        "",
        "Total:   SEVERE :    0  WARNING :    0",
        "",
        "createDomain.sh completed successfully (exit code = 0)"
```

functional validation of OAM components will be done later.  
Nevertheless, we are using `WDT` _only_  for domain creation and base mechanics. OAM specific bits are done afterwards, using scripts i've developed using `wlst` 

when would you be able to make a release?

**Comment by zeusbaba** [comment]
> My suggestion is we focus on making the JRF domain creation work properly. WDT does not officially support OAM so once the JRF use case is working, you should be able to use a valid typedef file for OAM and have it work properly.
> 
> What fields are needed in the typedef file to create a domain with RCU schemas has not changed. I suppose it is possible that WDT 1.9.x might have been more tolerant of typedef file omissions/errors but that doesn't constitute a regression in my mind.

thnx @robertpatrick sure, i'll follow your suggestion and experiment further.  
for OAM; we are using `WDT` _only_  for base domain creation and the mechanics. OAM specific bits are done via custom scripts using `WLST`

**Comment by zeusbaba** [comment]
> > Oh I see the problem. I do the reset before the topology is created, so set targets failed. Can you try this again. I don't have an easy way to test OAM.
> > [weblogic-deploy.zip](https://github.com/oracle/weblogic-deploy-tooling/files/12861819/weblogic-deploy.zip)
> 
> good news @jshum2479 :) this version worked fine and created domain successfully 🥇
> 
> ```
> "Issue Log for createDomain version 3.2.6-SNAPSHOT running WebLogic version 12.2.1.4.0.230702 offline mode:",
>         "",
>         "Total:   SEVERE :    0  WARNING :    0",
>         "",
>         "createDomain.sh completed successfully (exit code = 0)"
> ```
> 
> functional validation of OAM components will be done later. Nevertheless, we are using `WDT` _only_ for domain creation and base mechanics. OAM specific bits are done afterwards, using scripts i've developed using `wlst`
> 
> when would you be able to make a release?

we are in process of upgrading to `WDT3` across all MW components.  
could you please  make a new release including this fix?   
@jshum2479 @robertpatrick

**Comment by robertpatrick** [comment]
@zeusbaba I will try to get a new release created tomorrow.

**Comment by robertpatrick** [comment]
@zeusbaba https://github.com/oracle/weblogic-deploy-tooling/releases/tag/release-3.2.6
