### ISSUE TITLE
error with custom typedef: selectTemplate(Oracle Restricted JRF) failed : Error adding Template

### ISSUE THREAD

**Issue by zeusbaba** [oracle/weblogic-deploy-tooling#1512]
While trying to add `Restricted JRF` extension templates to `WebLogic`, I get this error  
```  
oracle.weblogic.deploy.create.CreateException: WLSDPLY-00040: selectTemplate(Oracle Restricted JRF) failed : Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle Restricted JRF name and null version
60708: Select a different template.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_create_exception$4(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:102) 
```   

using `WDT 3.4.0` 
Could you please help/advise?  
 
and here is the section from custom `typedef` 
```
"WLS_12CR2": {
      "baseTemplate": "Basic WebLogic Server Domain",
      "extensionTemplates": [
        "WebLogic Coherence Cluster Extension",
        "Oracle Restricted JRF",
        "Oracle Enterprise Manager-Restricted JRF"
      ],
      "customExtensionTemplates": [ ],
      "serverGroupsToTarget": [ "JRF-MAN-SVR", "WSM-CACHE-SVR", "JRF-WS-CORE-MAN-SVR"],
      "dynamicClusterServerGroupsToTarget" : [ "WSM-CACHE-DYN-CLUSTER" ],
      "rcuSchemas": [ ],
      "isJrfInstalled": true
    },
```  

and here is the full section of the log rel to error  
```
####<Nov 16, 2023 6:40:49 AM> <FINER> <DomainCreator> <__create_base_domain_with_select_template> <> <RETURN>
####<Nov 16, 2023 6:40:49 AM> <FINER> <DomainCreator> <__extend_domain_with_select_template> <> <ENTRY /u01/elhwls/domain/elhwls_domain>
####<Nov 16, 2023 6:40:49 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12211> <Selecting extension template named WebLogic Coherence Cluster Extension>
####<Nov 16, 2023 6:40:49 AM> <FINER> <WlstHelper> <select_template> <> <ENTRY WebLogic Coherence Cluster Extension>
####<Nov 16, 2023 6:40:49 AM> <FINER> <WlstHelper> <select_template> <> <RETURN>
####<Nov 16, 2023 6:40:49 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12211> <Selecting extension template named Oracle Restricted JRF>
####<Nov 16, 2023 6:40:49 AM> <FINER> <WlstHelper> <select_template> <> <ENTRY Oracle Restricted JRF>
####<Nov 16, 2023 6:40:49 AM> <FINER> <WlstHelper> <select_template> <> <THROW
oracle.weblogic.deploy.create.CreateException: WLSDPLY-00040: selectTemplate(Oracle Restricted JRF) failed : Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle Restricted JRF name and null version
60708: Select a different template.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_create_exception$4(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:102)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at org.python.core.PyObject._callextra(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_exception$2(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:74)
        at wlsdeploy.exception.exception_helper$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at wlsdeploy.tool.util.wlst_helper$py.select_template$33(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:676)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:199)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at wlsdeploy.tool.create.domain_creator$py._DomainCreator__extend_domain_with_select_template$19(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py:632)
        at wlsdeploy.tool.create.domain_creator$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:199)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at wlsdeploy.tool.create.domain_creator$py._DomainCreator__create_domain$12(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py:461)
        at wlsdeploy.tool.create.domain_creator$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:199)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at wlsdeploy.tool.create.domain_creator$py.create$3(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py:191)
        at wlsdeploy.tool.create.domain_creator$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/create/domain_creator.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:199)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at org.python.pycode._pyx33.main$10(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/create.py:400)
        at org.python.pycode._pyx33.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/create.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:181)
        at wlsdeploy.util.tool_main$py.run_tool$1(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/util/tool_main.py:52)
        at wlsdeploy.util.tool_main$py.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/util/tool_main.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:193)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at org.python.pycode._pyx33.f$0(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/create.py:430)
        at org.python.pycode._pyx33.call_function(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/create.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyCode.call(Unknown Source)
        at org.python.core.Py.runCode(Py.java:1226)
        at org.python.util.PythonInterpreter.execfile(Unknown Source)
        at weblogic.management.scripting.WLST.main(WLST.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at weblogic.WLST.main(WLST.java:47)
Caused by: com.oracle.cie.domain.script.jython.WLSTException: Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle Restricted JRF name and null version
60708: Select a different template.
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.python.core.PyReflectedFunction.__call__(Unknown Source)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyInstance.invoke(Unknown Source)
        at org.python.pycode._pyx5.command$1(/tmp/WLSTOfflineIni3611530985988384202.py:19)
        at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni3611530985988384202.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:188)
        at org.python.pycode._pyx5.selectTemplate$5(/tmp/WLSTOfflineIni3611530985988384202.py:33)
        at org.python.pycode._pyx5.call_function(/tmp/WLSTOfflineIni3611530985988384202.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(PyFunction.java:181)
        at wlsdeploy.tool.util.wlst_helper$py.select_template$33(/u01/binaries/elhwls/wdt/3.4.0/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:674)
        ... 59 more
Caused by: com.oracle.cie.domain.script.ScriptException: Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle Restricted JRF name and null version
60708: Select a different template.
        at com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:243)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:732)
        ... 80 more
Caused by: com.oracle.cie.domain.script.jython.WLSTException: Error adding Template:
60708: Template not found.
60708: Found no templates with Oracle Restricted JRF name and null version
...
```

**Comment by zeusbaba** [comment]
hi again,  
I think I found the reason.  
WLS component installation was using _only_  `WebLogic Server`  binaries.   
I just added `Fusion Middleware Infrastructure` install as well.  

that resolved the problem, closing this issue.  
thanks for your attention  

Yilmaz
