### ISSUE TITLE
Unable to convert argument to type java.lang.Class

### ISSUE THREAD

**Issue by piyushwadhwani** [oracle/weblogic-deploy-tooling#157]
Version:  The WebLogic Deploy Tooling createDomain version is 0.12:master
I see this attribute is defined in SecurityConfiguration.json

If anyone can point me direction what might be the issue , i would be happy to fix it and do a pull request

I am trying to create domain with ActiveDirectoryAuthenticator.
when i add certain attributes i get this exception 

In my model file i have provided UseRetrievedUserNameAsPrincipal: false

Caused by: oracle.weblogic.deploy.util.PyWLSTException: WLSDPLY-00008: wlst.set(UseRetrievedUserNameAsPrincipal, false) in offline mode failed : Unable to convert argument to type java.lang.Class
 @com.oracle.cie.domain.script.jython.WLScriptContext.set(WLScriptContext.java:2544)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
        at org.python.core.PyJavaInstance.__init__(Unknown Source)
        at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
        at org.python.core.PyObject.__call__(Unknown Source)
        at wlsdeploy.exception.exception_helper$py.create_pywlst_exception$8(/app/local/oracle/fmw12.2.1/installer/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:212)
        at wlsdeploy.exception.exception_helper$py.call_function(/app/local/oracle/fmw12.2.1/installer/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(Unknown Source)
        at wlsdeploy.util.wlst_helper$py.set$3(/app/local/oracle/fmw12.2.1/installer/weblogic-deploy/lib/python/wlsdeploy/util/wlst_helper.py:70)
        at wlsdeploy.util.wlst_helper$py.call_function(/app/local/oracle/fmw12.2.1/installer/weblogic-deploy/lib/python/wlsdeploy/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyTableCode.call(Unknown Source)
        at org.python.core.PyFunction.__call__(Unknown Source)
        at org.python.core.PyObject.invoke(Unknown Source)
        at wlsdeploy.tool.util.wlst_helper$py.set$5(/app/local/oracle/fmw12.2.1/installer/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:72)
        ... 129 more
Caused by: com.oracle.cie.domain.script.jython.WLSTException: Unable to convert argument to type java.lang.Class
 @com.oracle.cie.domain.script.jython.WLScriptContext.set(WLScriptContext.java:2544)

**Comment by CarolynRountree** [comment]
Looking at this issue. Would you attach the model file to this issue please? If you do not wish to attach the full model because of clear text values, then swipe the ActiveDirectoryAuthenticator section please.

**Comment by piyushwadhwani** [comment]
@CarolynRountree thanks for the help
[model.yml.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2358401/model.yml.txt)

**Comment by CarolynRountree** [comment]
Thank you. Able to recreate. This issue will need to be fixed internally.

**Comment by CarolynRountree** [comment]
Closed by pull request #159

**Comment by dborysenko** [comment]
Hi @CarolynRountree 
Same error occurs in ActiveDirectoryAuthenticator when I set:
UseTokenGroupsForGroupMembershipLookup: true
