### ISSUE TITLE
Validation unit test provides no information

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#165]
I have a failed validation unit test because of a bad return code from the validation tool. However, there is not information to determine what part of the test yaml file is the cause of the validation failure. Unit tests should ideally call methods within the tool to test different aspects and not a complete begin to end run of the tool, which is more of a system test - a system test would also be injected with the tool logging to produce critical information about failure and not just that the tool ended with a bad return code.

Traceback (most recent call last):
  File "C:\oracle\wls12213\wlserver\common\wlst\modules\jython-modules.jar\Lib/unittest.py", line 213, in __call__
  File "C:\Users\crountre\workspace\temp\weblogic-deploy-tooling\core\target\wlst-tests\test\.\validation_test.py", line 71, in testModelValidation
    self.assertNotEqual(return_code, Validator.ReturnCode.STOP)
  File "C:\oracle\wls12213\wlserver\common\wlst\modules\jython-modules.jar\Lib/unittest.py", line 294, in failIfEqual
AssertionError: 1 == 1

**Comment by CarolynRountree** [comment]
No time to do this change.

**Comment by CarolynRountree** [comment]
New team involved

**Comment by rakillen** [comment]
Converted to Jira WDT-284
