### ISSUE TITLE
NullPointerException due to white spaces in model yaml file

### ISSUE THREAD

**Issue by ankedia** [oracle/weblogic-deploy-tooling#208]
I encountered below NPE error when trying to create domain using WDT. I'll attach the model yaml file and domain properties file.

####<Jan 7, 2019 7:52:22 PM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /u01/oracle/properties/simple-topology.yaml at line 35 position 16: mismatched input ' ' expecting {NULL, BOOLEAN, INTEGER, FLOAT, NAME, UNQUOTED_STRING, QUOTED_STRING, LSQ_BRACKET}>
####<Jan 7, 2019 7:52:22 PM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /u01/oracle/properties/simple-topology.yaml at line 35 position 16: extraneous input '                ' expecting {NAME, LIST_ITEM_OP, DEDENT}>
####<Jan 7, 2019 7:52:22 PM> <SEVERE> <ParsingErrorListener> <syntaxError> <WLSDPLY-18018> <Parse error for file /u01/oracle/properties/simple-topology.yaml at line 45 position 0: extraneous input '\n' expecting {<EOF>, NAME, LIST_ITEM_OP}>
####<Jan 7, 2019 7:52:22 PM> <SEVERE> <AbstractYamlTranslator> <getScalarValue> <WLSDPLY-18006> <Field JdbcResource value had unexpected type: class name is oracle.weblogic.deploy.yaml.YamlParser$ValueContext>
Problem invoking WLST - Traceback (innermost last):
 File "/u01/weblogic-deploy/lib/python/create.py", line 398, in ?
 File "/u01/weblogic-deploy/lib/python/create.py", line 354, in main
 File "/u01/weblogic-deploy/lib/python/wlsdeploy/util/model_translator.py", line 42, in parse
 File "/u01/weblogic-deploy/lib/python/wlsdeploy/util/model_translator.py", line 77, in _parse_yaml
 File "/u01/weblogic-deploy/lib/python/wlsdeploy/yaml/yaml_translator.py", line 51, in parse
       at java.util.Hashtable.put(Hashtable.java:460)
       at oracle.weblogic.deploy.util.PyOrderedDict.__setitem__(PyOrderedDict.java:284)
       at oracle.weblogic.deploy.yaml.AbstractYamlTranslator.enterAssign(AbstractYamlTranslator.java:75)
       at oracle.weblogic.deploy.yaml.YamlParser$AssignContext.enterRule(YamlParser.java:262)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
       at oracle.weblogic.deploy.yaml.AbstractYamlTranslator.parseInternal(AbstractYamlTranslator.java:183)
       at oracle.weblogic.deploy.yaml.YamlTranslator.parse(YamlTranslator.java:60)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.NullPointerException: java.lang.NullPointerException

createDomain.sh completed but with some issues (exit code = 1)

**Comment by ankedia** [comment]
[simple-topology.zip](https://github.com/oracle/weblogic-deploy-tooling/files/2734630/simple-topology.zip)

**Comment by ankedia** [comment]
The line number specified in above error is 35 but the whitespaces were on line 34. It would be good to indicate the correct line number in error message. Thanks.
