### ISSUE TITLE
Discovery error on clustered configuration in wls 12.1.3

### ISSUE THREAD

**Issue by wapophis** [oracle/weblogic-deploy-tooling#294]
Given a cluster configured and running using wls 12.1.3, and using the release 0.20 when i try to discover the domain configuration then i'm having the error message below.

####<20-mar-2019 22:27:15> <INFORMACIÓN> <TopologyDiscoverer> <get_clusters> <WLSDPLY-06602> <Adding Cluster arq_cluster>
Problem invoking WLST - Traceback (innermost last):
  File "/home/oraarq/weblogic-deploy/lib/python/discover.py", line 527, in ?
  File "/home/oraarq/weblogic-deploy/lib/python/discover.py", line 504, in main
  File "/home/oraarq/weblogic-deploy/lib/python/discover.py", line 221, in __discover
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 64, in discover
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py", line 108, in get_clusters
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 465, in _discover_subfolders
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 444, in _discover_subfolder
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 320, in _discover_subfolder_singleton
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/tool/discover/discoverer.py", line 200, in _mbean_names_exist
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/util/wlst_helper.py", line 293, in lsc
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/util/wlst_helper.py", line 334, in _ls
  File "/home/oraarq/weblogic-deploy/lib/python/wlsdeploy/util/wlst_helper.py", line 58, in cd
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

oracle.weblogic.deploy.util.PyWLSTException: oracle.weblogic.deploy.util.PyWLSTException: WLSDPLY-00002: wlst.cd(/Cluster/arq_cluster/DatabaseLessLeasingBasis) in offline mode failed: com.oracle.cie.domain.script.ScriptException: No nested element DatabaseLessLeasingBasi is found

**Comment by CarolynRountree** [comment]
This is a WLST bug. It is possible discover this MBean in 12.2.1.3, but not in12.1.3 (I tested this). We will explore to see if we can find any support information for this problem.

**Comment by wapophis** [comment]
Thanks, waiting for your news about this.

**Comment by ddsharpe** [comment]
It is possible to apply a patch to the WLS install to fix this issue.  But, we found a workaround and are trying to include the workaround in WDT rather than requiring the patch.
