### ISSUE TITLE
Running deployApps.sh and getting out of java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sorenlloyd** [oracle/weblogic-deploy-tooling#462]
Looks like the process is running out of memory getting the hash of a large file, no doubt one of my  ear files. 

Can i easily give it more memory without editing the deployApps.sh file?

Problem invoking WLST - Traceback (innermost last):
  File "/home/oracle/wdt/weblogic-deploy/lib/python/deploy.py", line 436, in ?
  File "/home/oracle/wdt/weblogic-deploy/lib/python/deploy.py", line 421, in main
  File "/home/oracle/wdt/weblogic-deploy/lib/python/deploy.py", line 219, in __deploy
  File "/home/oracle/wdt/weblogic-deploy/lib/python/deploy.py", line 264, in __deploy_online
  File "/home/oracle/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/model_deployer.py", line 51, in deploy_applications
  File "/home/oracle/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 68, in deploy
  File "/home/oracle/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 214, in _ApplicationsDeployer__online_deploy_apps_and_libs
  File "/home/oracle/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 413, in _ApplicationsDeployer__get_existing_apps
  File "/home/oracle/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 603, in _ApplicationsDeployer__get_file_hash
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at oracle.weblogic.deploy.util.FileUtils.readInputStreamToByteArray(FileUtils.java:615)
	at oracle.weblogic.deploy.util.FileUtils.readFileToByteArray(FileUtils.java:593)
	at oracle.weblogic.deploy.util.FileUtils.computeHash(FileUtils.java:561)
	at oracle.weblogic.deploy.util.FileUtils.computeHash(FileUtils.java:541)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space

**Comment by sorenlloyd** [comment]
I got around this for the moment by editing commBaseEnv.sh

**Comment by CarolynRountree** [comment]
You can add the same system properties to the deployApps script without changing the script by setting your memory arguments on this environment variable: WLSDEPLOY_PROPERTIES

```
SET WLSDEPLOY_PROPERTIES="-Xms1536m -Xmx1536m -XX:MaxPermSize=512m"
```
