### ISSUE TITLE
ConcurrentModificationException performing an online deployment

### ISSUE THREAD

**Issue by sorenlloyd** [oracle/weblogic-deploy-tooling#469]
I'm getting a ConcurrentModificationException performing an online deployment using the toolset.  Offline is working ok.

Do you have any recommendations about how to get around this issue?

Thx

####<Oct 24, 2019 7:33:22 PM> <INFO> <ApplicationDeployer> <remove_app_from_deployment> <WLSDPLY-09311> <client_name_removed_ca has already been deployed, it will not be redeployed since the binary file has not changed>
Problem invoking WLST - Traceback (innermost last):
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py", line 436, in ?
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py", line 421, in main
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py", line 219, in __deploy
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py", line 264, in __deploy_online
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/model_deployer.py", line 51, in deploy_applications
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 68, in deploy
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 234, in _ApplicationsDeployer__online_deploy_apps_and_libs
  File "/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py", line 561, in _ApplicationsDeployer__build_app_deploy_strategy
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at oracle.weblogic.deploy.util.PyOrderedDict$PyOrderedDictIter.next(PyOrderedDict.java:604)
	at oracle.weblogic.deploy.util.PyOrderedDict$PyOrderedDictIter.__iternext__(PyOrderedDict.java:586)
	at wlsdeploy.tool.deploy.applications_deployer$py._ApplicationsDeployer__build_app_deploy_strategy$12(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py:561)
	at wlsdeploy.tool.deploy.applications_deployer$py.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.deploy.applications_deployer$py._ApplicationsDeployer__online_deploy_apps_and_libs$6(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py:234)
	at wlsdeploy.tool.deploy.applications_deployer$py.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.deploy.applications_deployer$py.deploy$3(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py:68)
	at wlsdeploy.tool.deploy.applications_deployer$py.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/applications_deployer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.deploy.model_deployer$py.deploy_applications$2(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/model_deployer.py:51)
	at wlsdeploy.tool.deploy.model_deployer$py.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/model_deployer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx36.__deploy_online$8(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py:264)
	at org.python.pycode._pyx36.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx36.__deploy$7(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py:219)
	at org.python.pycode._pyx36.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx36.main$13(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py:421)
	at org.python.pycode._pyx36.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx36.f$0(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py:436)
	at org.python.pycode._pyx36.call_function(/mnt/Oracle/nfs/weblogic-deployment/weblogic-deploy/lib/python/deploy.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyCode.call(Unknown Source)
	at org.python.core.Py.runCode(Py.java:1226)
	at org.python.util.PythonInterpreter.execfile(Unknown Source)
	at weblogic.management.scripting.WLST.main(WLST.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at weblogic.WLST.main(WLST.java:47)

java.util.ConcurrentModificationException: java.util.ConcurrentModificationException

**Comment by CarolynRountree** [comment]
What release of weblogic-deploy-tooling are you using? Could you provide your command line, and your model file, archive file (if possible).

**Comment by sorenlloyd** [comment]
I'm using 1.4.0, I can send you the rest internally at Oracle if you need it.

**Comment by sorenlloyd** [comment]
During testing I was repeatedly deploying the same ears.  The error took place when i did this in an online manner.  This is not the most likely scenario in real life.  Once i passed in a different ear the error no longer took place.   I also wrote some code to handle the exception in case a user does deploy the same ear.  Thanks Carolyn!
