### ISSUE TITLE
Fail to discover correct kss CustomIdentityKeyStoreFileName

### ISSUE THREAD

**Issue by ylora2020** [oracle/weblogic-deploy-tooling#513]
I created opss keystore with EM, and set weblogic server configuration for CustomIdentityKeyStoreType as "kss" and CustomIdentityKeyStoreFileName as "kss://system/ylidentity". When I tried to run "discoverDomain.sh ... -domain_type JRF", I got following error:
```
####<Dec 13, 2019 6:33:59 PM> <FINER> <Discoverer> <_populate_model_parameters> <WLSDPLY-06105> <Processing attribute CustomIdentityKeyStoreFileName value kss://system/ylidentity retrieved from location /Server/server_1>
...
####<Dec 13, 2019 6:33:59 PM> <FINER> <TopologyDiscoverer> <_add_server_keystore_file_to_archive> <> <ENTRY server_1 oracle.weblogic.deploy.util.WLSDeployArchive@65fbd6b /u01/data/domains/mydomain/kss:/system/ylidentity>
####<Dec 13, 2019 6:33:59 PM> <FINER> <TopologyDiscoverer> <_add_server_keystore_file_to_archive> <WLSDPLY-06623> <Adding keystore file /u01/data/domains/mydomain/kss:/system/ylidentity for server server_1 to archive file>
####<Dec 13, 2019 6:33:59 PM> <FINER> <WLSDeployArchive> <addServerKeyStoreFile> <> <ENTRY server_1 /u01/data/domains/mydomain/kss:/system/ylidentity>
####<Dec 13, 2019 6:33:59 PM> <FINER> <WLSDeployArchive> <validateNonEmptyString> <> <ENTRY server_1 serverName addServerKeyStoreFile>
####<Dec 13, 2019 6:33:59 PM> <FINER> <WLSDeployArchive> <validateNonEmptyString> <> <RETURN>
####<Dec 13, 2019 6:33:59 PM> <FINER> <WLSDeployArchive> <validateExistingFile> <> <ENTRY /u01/data/domains/mydomain/kss:/system/ylidentity keyStoreFile /tmp/tmp.adxfgUSGJp/DiscoveredDomain.zip addServerKeyStoreFile false>
####<Dec 13, 2019 6:33:59 PM> <FINER> <WLSDeployArchive> <validateExistingFile> <> <THROW
java.lang.IllegalArgumentException: WLSDeployArchive /tmp/tmp.adxfgUSGJp/DiscoveredDomain.zip unable to add file /u01/data/domains/mydomain/kss:/system/ylidentity to the archive because the file does not exist
        at oracle.weblogic.deploy.util.WLSDeployArchive.validateExistingFile(WLSDeployArchive.java:1308)
        at oracle.weblogic.deploy.util.WLSDeployArchive.validateExistingFile(WLSDeployArchive.java:1293)
        at oracle.weblogic.deploy.util.WLSDeployArchive.addServerKeyStoreFile(WLSDeployArchive.java:826)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.python.core.PyReflectedFunction.__call__(Unknown Source)
        at org.python.core.PyMethod.__call__(Unknown Source)
        at org.python.core.PyObject.__call__(Unknown Source)
        at org.python.core.PyInstance.invoke(Unknown Source)
        at wlsdeploy.tool.discover.topology_discoverer$py._add_server_keystore_file_to_archive$26(/u01/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:654)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/u01/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
...
...
>
####<Dec 13, 2019 6:33:59 PM> <WARNING> <TopologyDiscoverer> <_add_server_keystore_file_to_archive> <WLSDPLY-06624> <Unable to locate and add Server server_1 keystore file /u01/data/domains/mydomain/kss:/system/ylidentity to the archive file : WLSDeployArchive /tmp/tmp.adxfgUSGJp/DiscoveredDomain.zip unable to add file /u01/data/domains/mydomain/kss:/system/ylidentity to the archive because the file does not exist>
```
I don't see any special code to handle "kss" in topology_discoverer.py.

**Comment by CarolynRountree** [comment]
Add code to check for kss keystore type and print message about non-support. Bug will be marked as an enhancement for future support of adding kss keystores to archive file and target domain.

**Comment by rakillen** [comment]
The message about non-support was added with PR #515.  Flagged this issue as an enhancement.

**Comment by robertpatrick** [comment]
No support for OPSS database configuration discovery.  Closing for now.
