### ISSUE TITLE
discoverDomain.cmd doesn't work

### ISSUE THREAD

**Issue by 11bluetree** [oracle/weblogic-deploy-tooling#690]
Hi, I'm using the tool 1.9.2 
when discoverDomain.cmd  excuted , this error appered.

```
C:\Users\Administrator>C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\bin\discoverDomain.cmd -oracle_home C:\Oracle\Middleware\Oracle_Home -domain_home C:\Oracle\Middleware\Oracle_Home\user_projects\domains\base_domain  -archive_file C:\Oracle\Middleware\Oracle_Home\base_domain.zip
JDK version is 11.0.8+10_LTS, setting JAVA_VENDOR to Sun...
JAVA_HOME = C:\Oracle\Java\JDK-11~1.8
WLST_EXT_CLASSPATH = C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\weblogic-deploy-core.jar
CLASSPATH = C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\weblogic-deploy-core.jar
WLST_PROPERTIES = -Dcom.oracle.cie.script.throwException=true -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig
C:\Oracle\Middleware\Oracle_Home\oracle_common\common\bin\wlst.cmd C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\discover.py -oracle_home C:\Oracle\Middleware\Oracle_Home -domain_home C:\Oracle\Middleware\Oracle_Home\user_projects\domains\base_domain  -archive_file C:\Oracle\Middleware\Oracle_Home\base_domain.zip
####<2020/07/28 15:45:11> <情報> <WLSDeployLoggingConfig> <<init>> <> <The discoverDomain program will write its log to C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\logs\discoverDomain.log>

WebLogic Scripting Tool(WLST)を初期化しています...

WebLogic Server Administration Scripting Shellへようこそ

使用可能なコマンドに関するヘルプを表示するには、help()と入力してください

####<2020/07/28 15:45:26> <情報> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling discoverDomain version is 1.9.2:master.2c10a57:Jul 27, 2020 15:04 UTC>
####<2020/07/28 15:45:26> <情報> <discover> <main> <WLSDPLY-06024> <No variable file provided. Model passwords will contain the token '-- FIX ME --'>
####<2020/07/28 15:45:30> <情報> <discover> <_get_domain_name> <WLSDPLY-06022> <Discover domain base_domain>
####<2020/07/28 15:45:30> <情報> <TopologyDiscoverer> <discover> <WLSDPLY-06600> <Discovering domain model topology>
####<2020/07/28 15:45:31> <情報> <TopologyDiscoverer> <_get_nm_properties> <WLSDPLY-06627> <Discovering NM Properties>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PyReflectedFunction (file:/C:/Oracle/Middleware/Oracle_Home/wlserver/modules/com.oracle.weblogic.internal.thirdparty.jython.jar) to method sun.nio.cs.MS932.newEncoder()
WARNING: Please consider reporting this to the maintainers of org.python.core.PyReflectedFunction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Traceback (most recent call last):
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 532, in <module>
    main(sys.argv)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 503, in main
    model = __discover(model_context, aliases, discover_injector, helper)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 503, in main
    model = __discover(model_context, aliases, discover_injector, helper)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 185, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 185, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 66, in discover
    self.discover_domain_parameters()
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 296, in discover_domain_parameters
    model_folder_name, folder_result = self._get_nm_properties()
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 371, in _get_nm_properties
    self._populate_model_parameters(result, location)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 103, in _populate_model_parameters
    wlst_lsa_params = self._get_attributes_for_current_location(location)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 187, in _get_attributes_for_current_location
    attributes = self._wlst_helper.lsa(path)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 187, in _get_attributes_for_current_location
    attributes = self._wlst_helper.lsa(path)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\util\wlst_helper.py", line 457, in lsa
    result = self.__ls(_method_name, 'a', path, log_throwing)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\util\wlst_helper.py", line 1471, in _WlstHelper__ls
    self.__logger.finest('WLSDPLY-00030', method_name, ls_type, current_path, result,
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 200, in finest
    record = self._get_log_record(JLevel.FINEST, clazz, method, message, error, *args)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 263, in _get_log_record
    record.setParameters(_get_args_as_java_array(*args))
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 289, in _get_args_as_java_array
    result.add(str(arg))
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.JavaProxyMap$2.__call__(JavaProxyMap.java:115)
        at org.python.core.PyObjectDerived.__repr__(PyObjectDerived.java:104)
        at org.python.core.PyObject$__repr___exposer.__call__(Unknown Source)
        at org.python.core.PyObjectDerived.__str__(PyObjectDerived.java:92)
        at org.python.core.PyString.str_new(PyString.java:168)
        at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
        at org.python.core.PyType.invokeNew(PyType.java:583)
        at org.python.core.PyType.type___call__(PyType.java:1815)
        at org.python.core.PyType.__call__(PyType.java:1805)
        at org.python.core.PyObject.__call__(PyObject.java:480)
        at org.python.core.PyObject.__call__(PyObject.java:484)
        at wlsdeploy.logging.platform_logger$py._get_args_as_java_array$26(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:290)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyFunction.function___call__(PyFunction.java:471)
        at org.python.core.PyFunction.__call__(PyFunction.java:466)
        at org.python.core.PyFunction.__call__(PyFunction.java:461)
        at org.python.core.PyObject._callextra(PyObject.java:620)
        at wlsdeploy.logging.platform_logger$py._get_log_record$25(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:278)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at org.python.core.PyMethod.__call__(PyMethod.java:223)
        at org.python.core.PyObject._callextra(PyObject.java:620)
        at wlsdeploy.logging.platform_logger$py.finest$20(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:202)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at wlsdeploy.tool.util.wlst_helper$py._WlstHelper__ls$76(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py:1473)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.__call__(PyMethod.java:187)
        at wlsdeploy.tool.util.wlst_helper$py.lsa$24(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py:471)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:146)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at wlsdeploy.tool.discover.discoverer$py._get_attributes_for_current_location$7(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py:192)
        at wlsdeploy.tool.discover.discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at wlsdeploy.tool.discover.discoverer$py._populate_model_parameters$4(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py:125)
        at wlsdeploy.tool.discover.discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
        at org.python.core.PyFunction.__call__(PyFunction.java:434)
        at org.python.core.PyMethod.__call__(PyMethod.java:156)
        at wlsdeploy.tool.discover.topology_discoverer$py._get_nm_properties$13(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:373)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at wlsdeploy.tool.discover.topology_discoverer$py.discover_domain_parameters$10(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:301)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at wlsdeploy.tool.discover.topology_discoverer$py.discover$3(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:105)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at org.python.pycode._pyx32.__discover$5(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:202)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:189)
        at org.python.core.PyFunction.__call__(PyFunction.java:446)
        at org.python.pycode._pyx32.main$15(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:527)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.pycode._pyx32.f$0(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:532)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1614)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at weblogic.management.scripting.WLST.main(WLST.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at weblogic.WLST.main(WLST.java:47)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
Problem invoking WLST - Traceback (most recent call last):
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 532, in <module>
    main(sys.argv)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 503, in main
    model = __discover(model_context, aliases, discover_injector, helper)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 503, in main
    model = __discover(model_context, aliases, discover_injector, helper)
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 185, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "C:\Oracle\Middleware\Oracle_Home\weblogic-deploy\lib\python\discover.py", line 185, in __discover
    TopologyDiscoverer(model_context, model.get_model_topology(), base_location, wlst_mode=__wlst_mode,
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 66, in discover
    self.discover_domain_parameters()
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 296, in discover_domain_parameters
    model_folder_name, folder_result = self._get_nm_properties()
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\topology_discoverer.py", line 371, in _get_nm_properties
    self._populate_model_parameters(result, location)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 103, in _populate_model_parameters
    wlst_lsa_params = self._get_attributes_for_current_location(location)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 187, in _get_attributes_for_current_location
    attributes = self._wlst_helper.lsa(path)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\discover\discoverer.py", line 187, in _get_attributes_for_current_location
    attributes = self._wlst_helper.lsa(path)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\util\wlst_helper.py", line 457, in lsa
    result = self.__ls(_method_name, 'a', path, log_throwing)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\tool\util\wlst_helper.py", line 1471, in _WlstHelper__ls
    self.__logger.finest('WLSDPLY-00030', method_name, ls_type, current_path, result,
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 200, in finest
    record = self._get_log_record(JLevel.FINEST, clazz, method, message, error, *args)
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 263, in _get_log_record
    record.setParameters(_get_args_as_java_array(*args))
  File "C:\Oracle\MIDDLE~1\ORACLE~1\WEBLOG~1\lib\python\wlsdeploy\logging\platform_logger.py", line 289, in _get_args_as_java_array
    result.add(str(arg))
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.JavaProxyMap$2.__call__(JavaProxyMap.java:115)
        at org.python.core.PyObjectDerived.__repr__(PyObjectDerived.java:104)
        at org.python.core.PyObject$__repr___exposer.__call__(Unknown Source)
        at org.python.core.PyObjectDerived.__str__(PyObjectDerived.java:92)
        at org.python.core.PyString.str_new(PyString.java:168)
        at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
        at org.python.core.PyType.invokeNew(PyType.java:583)
        at org.python.core.PyType.type___call__(PyType.java:1815)
        at org.python.core.PyType.__call__(PyType.java:1805)
        at org.python.core.PyObject.__call__(PyObject.java:480)
        at org.python.core.PyObject.__call__(PyObject.java:484)
        at wlsdeploy.logging.platform_logger$py._get_args_as_java_array$26(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:290)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyFunction.function___call__(PyFunction.java:471)
        at org.python.core.PyFunction.__call__(PyFunction.java:466)
        at org.python.core.PyFunction.__call__(PyFunction.java:461)
        at org.python.core.PyObject._callextra(PyObject.java:620)
        at wlsdeploy.logging.platform_logger$py._get_log_record$25(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:278)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at org.python.core.PyMethod.__call__(PyMethod.java:223)
        at org.python.core.PyObject._callextra(PyObject.java:620)
        at wlsdeploy.logging.platform_logger$py.finest$20(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py:202)
        at wlsdeploy.logging.platform_logger$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/logging/platform_logger.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at wlsdeploy.tool.util.wlst_helper$py._WlstHelper__ls$76(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py:1473)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.__call__(PyMethod.java:187)
        at wlsdeploy.tool.util.wlst_helper$py.lsa$24(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py:471)
        at wlsdeploy.tool.util.wlst_helper$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/util/wlst_helper.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:146)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at wlsdeploy.tool.discover.discoverer$py._get_attributes_for_current_location$7(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py:192)
        at wlsdeploy.tool.discover.discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at wlsdeploy.tool.discover.discoverer$py._populate_model_parameters$4(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py:125)
        at wlsdeploy.tool.discover.discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
        at org.python.core.PyFunction.__call__(PyFunction.java:434)
        at org.python.core.PyMethod.__call__(PyMethod.java:156)
        at wlsdeploy.tool.discover.topology_discoverer$py._get_nm_properties$13(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:373)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at wlsdeploy.tool.discover.topology_discoverer$py.discover_domain_parameters$10(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:301)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at wlsdeploy.tool.discover.topology_discoverer$py.discover$3(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:105)
        at wlsdeploy.tool.discover.topology_discoverer$py.call_function(C:/Oracle/MIDDLE~1/ORACLE~1/WEBLOG~1/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.core.PyMethod.__call__(PyMethod.java:126)
        at org.python.pycode._pyx32.__discover$5(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:202)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:189)
        at org.python.core.PyFunction.__call__(PyFunction.java:446)
        at org.python.pycode._pyx32.main$15(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:527)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.pycode._pyx32.f$0(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py:532)
        at org.python.pycode._pyx32.call_function(C:/Oracle/Middleware/Oracle_Home/weblogic-deploy/lib/python/discover.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1614)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at weblogic.management.scripting.WLST.main(WLST.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at weblogic.WLST.main(WLST.java:47)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value


discoverDomain.cmd completed but with some issues (exit code = 1)
```

**Environment**
OS: windows 2019 standard 64bit
Locale: Japanese
Encode: Shift-Jis
JDK: Oracle JDK-11.0.8
WLS: 14.1.1.0

I think 「Cannot create PyString with non-byte value」is most important issues.
Please help me to resolve this issue.

Haru.

**Comment by ddsharpe** [comment]
@11bluetree we are looking into this now.

**Comment by CarolynRountree** [comment]
Work in progress

**Comment by ddsharpe** [comment]
#694 fixes the issue with the logging of the WLST message seen in your trace here.  This fix will be in the next bug release this week.  Please let us know if you have any further issues.

**Comment by 11bluetree** [comment]
@ddsharpe 
I checked new release. Thanks so much!
