### ISSUE TITLE
SOA domain issue

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#724]
I tried to create a SOA doamin. However, when I executed discoverDomain.sh, I got this warning message.

`       1. WLSDPLY-06779: Unable to complete discover of Security Configuration Provider Proxy for Trust Service Identity Asserter: Name=Trust Service Identity Asserter, Type=AuthenticationProvider. The mbean type jar and schema jar must be in the correct locations to discover the custom provider MBean. See documentation for more information.`

I ignored the warning and I executed createDomain.sh. However, when I tried to startup the AdminServer, the server did not start because of an error related to AuthenticationProviders. Importantly, the domain I used as a source to execute discoverDomain.sh is up and running without any AuthenticationProviders issue.

I am using OFM 12.2.1.4 and weblogic-deploy-tooling 1.9.5

**Comment by textanalyticsman** [comment]
Do you have any news about this? We cannot install SOA because of this.

**Comment by CarolynRountree** [comment]
JRF installs a Security Provider called Trust Identity Security Provider. In order to deal with the security provider in offline WLST (during createDomain), a schematype jar needs to be installed into the correct location. You can generate this jar file and install it into the correct location using the directions found here: https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/use_cases.md#modeling-security-providers

We have opened a bug with the Oracle install team to get this jar added to the install. Bug 31710534

**Comment by textanalyticsman** [comment]
Thank you so much.

**Comment by textanalyticsman** [comment]
After following your instructions the domain has been created without any warning and/or error message. However, when I tried to start the AdminServer, I got this.

> <06-Sep-2020 15:41:59,769 o'clock CEST> <Error> <Security> <BEA-090870> <The realm "myrealm" failed to be loaded: weblogic.security.service.SecurityServiceException: com.bea.common.engine.ServiceInitializationException: com.bea.common.engine.SecurityServiceRuntimeException: [Security:097533]SecurityProvider service class name for Trust Service Identity Asserter is not specified..
weblogic.security.service.SecurityServiceException: com.bea.common.engine.ServiceInitializationException: com.bea.common.engine.SecurityServiceRuntimeException: [Security:097533]SecurityProvider service class name for Trust Service Identity Asserter is not specified.
        at weblogic.security.service.CSSWLSDelegateImpl.initializeServiceEngine(CSSWLSDelegateImpl.java:341)
        at weblogic.security.service.CSSWLSDelegateImpl.initialize(CSSWLSDelegateImpl.java:218)
        at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.InitializeServiceEngine(CommonSecurityServiceManagerDelegateImpl.java:2017)
        at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.initializeRealm(CommonSecurityServiceManagerDelegateImpl.java:499)
        at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.loadRealm(CommonSecurityServiceManagerDelegateImpl.java:846)
        Truncated. see log file for complete stacktrace
Caused By: com.bea.common.engine.ServiceInitializationException: com.bea.common.engine.SecurityServiceRuntimeException: [Security:097533]SecurityProvider service class name for Trust Service Identity Asserter is not specified.
        at com.bea.common.engine.internal.ServiceEngineImpl.findOrStartService(ServiceEngineImpl.java:365)
        at com.bea.common.engine.internal.ServiceEngineImpl.findOrStartService(ServiceEngineImpl.java:315)
        at com.bea.common.engine.internal.ServiceEngineImpl.lookupService(ServiceEngineImpl.java:257)
        at com.bea.common.engine.internal.ServicesImpl.getService(ServicesImpl.java:72)
        at weblogic.security.service.internal.WLSIdentityServiceImpl.initialize(WLSIdentityServiceImpl.java:47)
        Truncated. see log file for complete stacktrace
Caused By: com.bea.common.engine.SecurityServiceRuntimeException: [Security:097533]SecurityProvider service class name for Trust Service Identity Asserter is not specified.
        at com.bea.common.security.internal.legacy.service.SecurityProviderImpl.init(SecurityProviderImpl.java:42)
        at com.bea.common.engine.internal.ServiceEngineImpl.findOrStartService(ServiceEngineImpl.java:363)
        at com.bea.common.engine.internal.ServiceEngineImpl.findOrStartService(ServiceEngineImpl.java:315)
        at com.bea.common.engine.internal.ServiceEngineImpl.lookupService(ServiceEngineImpl.java:257)
        at com.bea.common.engine.internal.ServicesImpl.getService(ServicesImpl.java:72)
        Truncated. see log file for complete stacktrace
>

**Comment by textanalyticsman** [comment]
Discard my last comment, I followed these steps to fix it.

# I created the file you pointed by following this https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/use_cases.md#modeling-security-providers

# I executed discoverDomain to get the model again.

# I executed createDomain and it partially works.

Now I have issues with wrong targets, but I will raise another ticket for this.

**Comment by rakillen** [comment]
Targeting issues are discussed in #729 , closing this issue.

**Comment by magVarv** [comment]
Dear @rakillen, 

we faced the same issue and tried to follow the before mentioned link : https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/use_cases.md#modeling-security-providers

This link does not work we are getting a 404 code when trying to access. 

Can you please assist us ? 

Best Regards

**Comment by rjnkmr** [comment]
The docs are moved, try: https://oracle.github.io/weblogic-deploy-tooling/samples/securityproviders-model/
