### ISSUE TITLE
Discovery domain online - WLSDPLY-00005: get(null) in online mode failed

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#784]
Hello,

I am trying to discover a domain online and I am getting errors detailed below.

I am using this command.

`/home/soa/weblogic-deploy/bin/discoverDomain.sh -oracle_home /u01/binaries/soa/fmw/12.1.3.0.0 -domain_home /u01/soa/domain/soa_domain -archive_file /home/soa/SOADomain.zip -model_file /home/soa/SOADomainModel.yaml -domain_type SOA -java_home /u01/binaries/soa/jdk/current -variable_file /home/soa/SOADomainModel.properties -admin_user weblogic -admin_url t3://localhost:7011 -wlst_path /u01/binaries/soa/fmw/12.1.3.0.0/soa`

The domain I am trying to introspect is a SOA domain 12.1.3.

####<Nov 17, 2020 7:15:58 PM> <FINER> <WlstHelper> <get> <> <THROW
oracle.weblogic.deploy.discover.DiscoverException: WLSDPLY-00005: get(null) in online mode failed: Error occurred while performing get : Error getting attribute null : Exception occured trying to get attribute of a ModelMBean 
Use dumpStack() to view the full stacktrace :w
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
	at org.python.core.PyJavaInstance.__init__(Unknown Source)
	at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
	at org.python.core.PyObject.__call__(Unknown Source)
	at wlsdeploy.exception.exception_helper$py.create_discover_exception$6(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:150)
	at wlsdeploy.exception.exception_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyObject._callextra(Unknown Source)
	at wlsdeploy.exception.exception_helper$py.create_exception$2(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:71)
	at wlsdeploy.exception.exception_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at wlsdeploy.tool.util.wlst_helper$py.get$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:90)
	at wlsdeploy.tool.util.wlst_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py._dynamic_server$28(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:772)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py.get_servers$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:157)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py.discover$3(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:76)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at org.python.pycode._pyx116.__discover$5(/home/elhsoa/weblogic-deploy/lib/python/discover.py:187)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.pycode._pyx116.main$15(/home/elhsoa/weblogic-deploy/lib/python/discover.py:519)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx116.f$0(/home/elhsoa/weblogic-deploy/lib/python/discover.py:544)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyCode.call(Unknown Source)
	at org.python.core.Py.runCode(Py.java:1226)
	at org.python.util.PythonInterpreter.execfile(Unknown Source)
	at weblogic.management.scripting.WLST.main(WLST.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at weblogic.WLST.main(WLST.java:29)
Caused by: org.python.proxies.main$WLSTException$1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.python.core.PyInstance.makeProxy(Unknown Source)
	at org.python.core.PyInstance.__init__(Unknown Source)
	at org.python.core.PyClass.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.pycode._pyx4.raiseWLSTException$29(<iostream>:550)
	at org.python.pycode._pyx4.call_function(<iostream>)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx117.get$34(<iostream>:546)
	at org.python.pycode._pyx117.call_function(<iostream>)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at wlsdeploy.tool.util.wlst_helper$py.get$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:88)
	... 58 more
Caused by: javax.management.RuntimeOperationsException: Exception occured trying to get attribute of a ModelMBean
	at weblogic.utils.StackTraceDisabled.unknownMethod()
Caused by: java.lang.IllegalArgumentException: attributeName must not be null or ""
	... 1 more

**Comment by CarolynRountree** [comment]
Could you provide the discoverDomain.log from the <install>/logs directory. If possible the config.xml for the domain.

**Comment by textanalyticsman** [comment]
I will check whether I can upload those files according to internal security policies.

I think below stack trace could be useful as apparently WDT "thinks" a managed server is dynamic.

####<Nov 17, 2020 7:15:58 PM> <FINE> <TopologyDiscoverer> <_dynamic_server> <WLSDPLY-06613> <Dynamic Server elhsoa_ms1 discovered in online mode will not be added to the model>
####<Nov 17, 2020 7:15:58 PM> <FINER> <WlstHelper> <get> <> <THROW
oracle.weblogic.deploy.discover.DiscoverException: WLSDPLY-00005: get(null) in online mode failed: Error occurred while performing get : Error getting attribute null : Exception occured trying to get attribute of a ModelMBean 
Use dumpStack() to view the full stacktrace :w
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.python.core.PyReflectedConstructor.__call__(Unknown Source)
	at org.python.core.PyJavaInstance.__init__(Unknown Source)
	at org.python.core.PyJavaClass.__call__(PyJavaClass.java:891)
	at org.python.core.PyObject.__call__(Unknown Source)
	at wlsdeploy.exception.exception_helper$py.create_discover_exception$6(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:150)
	at wlsdeploy.exception.exception_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyObject._callextra(Unknown Source)
	at wlsdeploy.exception.exception_helper$py.create_exception$2(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py:71)
	at wlsdeploy.exception.exception_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/exception/exception_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at wlsdeploy.tool.util.wlst_helper$py.get$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:90)
	at wlsdeploy.tool.util.wlst_helper$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py._dynamic_server$28(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:772)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py.get_servers$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:157)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at wlsdeploy.tool.discover.topology_discoverer$py.discover$3(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py:76)
	at wlsdeploy.tool.discover.topology_discoverer$py.call_function(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/discover/topology_discoverer.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject.invoke(Unknown Source)
	at org.python.pycode._pyx116.__discover$5(/home/elhsoa/weblogic-deploy/lib/python/discover.py:187)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.pycode._pyx116.main$15(/home/elhsoa/weblogic-deploy/lib/python/discover.py:519)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx116.f$0(/home/elhsoa/weblogic-deploy/lib/python/discover.py:544)
	at org.python.pycode._pyx116.call_function(/home/elhsoa/weblogic-deploy/lib/python/discover.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyCode.call(Unknown Source)
	at org.python.core.Py.runCode(Py.java:1226)
	at org.python.util.PythonInterpreter.execfile(Unknown Source)
	at weblogic.management.scripting.WLST.main(WLST.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at weblogic.WLST.main(WLST.java:29)
Caused by: org.python.proxies.main$WLSTException$1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.python.core.PyInstance.makeProxy(Unknown Source)
	at org.python.core.PyInstance.__init__(Unknown Source)
	at org.python.core.PyClass.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.pycode._pyx4.raiseWLSTException$29(<iostream>:550)
	at org.python.pycode._pyx4.call_function(<iostream>)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.pycode._pyx117.get$34(<iostream>:546)
	at org.python.pycode._pyx117.call_function(<iostream>)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at wlsdeploy.tool.util.wlst_helper$py.get$5(/home/elhsoa/weblogic-deploy/lib/python/wlsdeploy/tool/util/wlst_helper.py:88)
	... 58 more
Caused by: javax.management.RuntimeOperationsException: Exception occured trying to get attribute of a ModelMBean
	at weblogic.utils.StackTraceDisabled.unknownMethod()
Caused by: java.lang.IllegalArgumentException: attributeName must not be null or ""
	... 1 more

>

**Comment by textanalyticsman** [comment]
I am attaching the log file.
[Uploading discoverDomainMod.log…]()

**Comment by textanalyticsman** [comment]
I am attaching the configuration file.


[config.xml.txt](https://github.com/oracle/weblogic-deploy-tooling/files/5558767/config.xml.txt)

**Comment by jshum2479** [comment]
I received your log file and config.xml and deleted them for security purpose

**Comment by jshum2479** [comment]
I can reproduce this, this only happens with a 12.1.3 domain.  Once we have a fix, we will let you know.
