### ISSUE TITLE
Failed Initializing weblogic admin server after updating domain

### ISSUE THREAD

**Issue by Bneve5** [oracle/weblogic-deploy-tooling#922]
After updating domain by adding another managed server to the cluster, I get 

`Total:       WARNING :     0    SEVERE :     0\r\rupdateDomain.sh completed successfully (exit code = 0)`

and after I restart the weblogic admin server I get this error:

```
<Jun 17, 2021 3:17:00 PM CEST> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: A MultiException has 9 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: create on weblogic.management.provider.internal.RuntimeAccessImpl
3. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.FinalThreadLocalService errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.FinalThreadLocalService
6. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.BootService errors were found
7. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.BootService
8. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.protocol.ProtocolService errors were found
9. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.protocol.ProtocolService

A MultiException has 9 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: create on weblogic.management.provider.internal.RuntimeAccessImpl
3. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.management.provider.internal.RuntimeAccessService
4. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.FinalThreadLocalService errors were found
5. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.FinalThreadLocalService
6. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.t3.srvr.BootService errors were found
7. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.t3.srvr.BootService
8. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.protocol.ProtocolService errors were found
9. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.protocol.ProtocolService

        at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:89)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:250)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused By: java.lang.NullPointerException
        at weblogic.utils.jars.JarFileUtils.addFilesToJar(JarFileUtils.java:79)
        at weblogic.utils.jars.JarFileUtils.addFilesToJar(JarFileUtils.java:102)
```

**Comment by CarolynRountree** [comment]
could you provide the model that you used for the update. Also, can you provide the updateDomain.log found in <weblogic-deploy>/logs

**Comment by Bneve5** [comment]
Solved it, needed the archive file.

**Comment by ddsharpe** [comment]
@Bneve5 Did you have something in the model that referenced something in the archive?  And the WDT update succeeded without a warning or error?
